;;; jargon.el --- Lookup entries in the Jargon File

;; Copyright (c) 2003 Lawrence Mitchell <wence@gmx.li>

;; COPYRIGHT NOTICE

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 2 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more
;; details. http://www.gnu.org/copyleft/gpl.html
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs. If you did not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave., Cambridge, MA 02139, USA.

;;; Commentary:
;; Lookup words in the jargon file.  To look up a word, do
;; M-x jargon-url RET.  You can then enter a term (with completion).

;;; Code:

(defvar jargon-words
  '(("(TM)" "0/TM.html")
    ("/dev/null" "0/dev-null.html")
    ("/me" "0/me.html")
    ("0" "0/numeral-zero.html")
    ("1TBS" "0/one-TBS.html")
    ("2" "0/infix-2.html")
    ("404" "0/code-404.html")
    ("404 compliant" "0/code-404-compliant.html")
    ("@-party" "0/at-party.html")
    ("abbrev" "A/abbrev.html")
    ("ABEND" "A/ABEND.html")
    ("accumulator" "A/accumulator.html")
    ("ACK" "A/ACK.html")
    ("Acme" "A/Acme.html")
    ("ad-hockery" "A/ad-hockery.html")
    ("address harvester" "A/address-harvester.html")
    ("adger" "A/adger.html")
    ("admin" "A/admin.html")
    ("ADVENT" "A/ADVENT.html")
    ("adware" "A/adware.html")
    ("AFAIK" "A/AFAIK.html")
    ("AFJ" "A/AFJ.html")
    ("AFK" "A/AFK.html")
    ("AI" "A/AI.html")
    ("AI-complete" "A/AI-complete.html")
    ("airplane rule" "A/airplane-rule.html")
    ("Alderson loop" "A/Alderson-loop.html")
    ("aliasing bug" "A/aliasing-bug.html")
    ("Alice and Bob" "A/Alice-and-Bob.html")
    ("All hardware sucks, all software sucks." "A/All-hardware-sucks--all-software-sucks-.html")
    ("all your base are belong to us" "A/all-your-base-are-belong-to-us.html")
    ("alpha geek" "A/alpha-geek.html")
    ("alpha particles" "A/alpha-particles.html")
    ("alt" "A/alt.html")
    ("alt bit" "A/alt-bit.html")
    ("Aluminum Book" "A/Aluminum-Book.html")
    ("ambimouseterous" "A/ambimouseterous.html")
    ("Amiga" "A/Amiga.html")
    ("Amiga Persecution Complex" "A/Amiga-Persecution-Complex.html")
    ("amp off" "A/amp-off.html")
    ("amper" "A/amper.html")
    ("and there was much rejoicing" "A/and-there-was-much-rejoicing.html")
    ("Angband" "A/Angband.html")
    ("angle brackets" "A/angle-brackets.html")
    ("angry fruit salad" "A/angry-fruit-salad.html")
    ("annoybot" "A/annoybot.html")
    ("annoyware" "A/annoyware.html")
    ("ANSI standard" "A/ANSI-standard.html")
    ("ANSI standard pizza" "A/ANSI-standard-pizza.html")
    ("anti-idiotarianism" "A/anti-idiotarianism.html")
    ("AOL!" "A/AOL-.html")
    ("app" "A/app.html")
    ("Archimedes" "A/Archimedes.html")
    ("arena" "A/arena.html")
    ("arg" "A/arg.html")
    ("ARMM" "A/ARMM.html")
    ("armor-plated" "A/armor-plated.html")
    ("asbestos" "A/asbestos.html")
    ("asbestos cork award" "A/asbestos-cork-award.html")
    ("asbestos longjohns" "A/asbestos-longjohns.html")
    ("ASCII" "A/ASCII.html")
    ("ASCII art" "A/ASCII-art.html")
    ("ASCIIbetical order" "A/ASCIIbetical-order.html")
    ("astroturfing" "A/astroturfing.html")
    ("atomic" "A/atomic.html")
    ("attoparsec" "A/attoparsec.html")
    ("Aunt Tillie" "A/Aunt-Tillie.html")
    ("AUP" "A/AUP.html")
    ("autobogotiphobia" "A/autobogotiphobia.html")
    ("autoconfiscate" "A/autoconfiscate.html")
    ("automagically" "A/automagically.html")
    ("avatar" "A/avatar.html")
    ("awk" "A/awk.html")
    ("B1FF" "B/B1FF.html")
    ("B5" "B/B5.html")
    ("back door" "B/back-door.html")
    ("backbone cabal" "B/backbone-cabal.html")
    ("backbone site" "B/backbone-site.html")
    ("backgammon" "B/backgammon.html")
    ("background" "B/background.html")
    ("backreference" "B/backreference.html")
    ("backronym" "B/backronym.html")
    ("backward combatability" "B/backward-combatability.html")
    ("BAD" "B/BAD.html")
    ("Bad and Wrong" "B/Bad-and-Wrong.html")
    ("Bad Thing" "B/Bad-Thing.html")
    ("bag on the side" "B/bag-on-the-side.html")
    ("bagbiter" "B/bagbiter.html")
    ("bagbiting" "B/bagbiting.html")
    ("baggy pantsing" "B/baggy-pantsing.html")
    ("balloonian variable" "B/balloonian-variable.html")
    ("bamf" "B/bamf.html")
    ("banana problem" "B/banana-problem.html")
    ("bandwidth" "B/bandwidth.html")
    ("bang" "B/bang.html")
    ("bang on" "B/bang-on.html")
    ("bang path" "B/bang-path.html")
    ("banner" "B/banner.html")
    ("banner ad" "B/banner-ad.html")
    ("banner site" "B/banner-site.html")
    ("bar" "B/bar.html")
    ("bare metal" "B/bare-metal.html")
    ("barf" "B/barf.html")
    ("barfmail" "B/barfmail.html")
    ("barfulation" "B/barfulation.html")
    ("barfulous" "B/barfulous.html")
    ("barn" "B/barn.html")
    ("barney" "B/barney.html")
    ("baroque" "B/baroque.html")
    ("BASIC" "B/BASIC.html")
    ("batbelt" "B/batbelt.html")
    ("batch" "B/batch.html")
    ("bathtub curve" "B/bathtub-curve.html")
    ("Batman factor" "B/Batman-factor.html")
    ("baud" "B/baud.html")
    ("baz" "B/baz.html")
    ("bazaar" "B/bazaar.html")
    ("bboard" "B/bboard.html")
    ("BBS" "B/BBS.html")
    ("BCPL" "B/BCPL.html")
    ("BDFL" "B/BDFL.html")
    ("beam" "B/beam.html")
    ("beanie key" "B/beanie-key.html")
    ("beep" "B/beep.html")
    ("Befunge" "B/Befunge.html")
    ("beige toaster" "B/beige-toaster.html")
    ("bells and whistles" "B/bells-and-whistles.html")
    ("bells whistles and gongs" "B/bells-whistles-and-gongs.html")
    ("benchmark" "B/benchmark.html")
    ("Berkeley Quality Software" "B/Berkeley-Quality-Software.html")
    ("Berzerkeley" "B/Berzerkeley.html")
    ("beta" "B/beta.html")
    ("BFI" "B/BFI.html")
    ("BI" "B/BI.html")
    ("bible" "B/bible.html")
    ("BiCapitalization" "B/BiCapitalization.html")
    ("biff" "B/biff.html")
    ("big iron" "B/big-iron.html")
    ("Big Red Switch" "B/Big-Red-Switch.html")
    ("Big Room" "B/Big-Room.html")
    ("big win" "B/big-win.html")
    ("big-endian" "B/big-endian.html")
    ("bignum" "B/bignum.html")
    ("bigot" "B/bigot.html")
    ("bikeshedding" "B/bikeshedding.html")
    ("binary four" "B/binary-four.html")
    ("bit" "B/bit.html")
    ("bit bashing" "B/bit-bashing.html")
    ("bit bucket" "B/bit-bucket.html")
    ("bit decay" "B/bit-decay.html")
    ("bit rot" "B/bit-rot.html")
    ("bit twiddling" "B/bit-twiddling.html")
    ("bit-paired keyboard" "B/bit-paired-keyboard.html")
    ("bitblt" "B/bitblt.html")
    ("bits" "B/bits.html")
    ("bitty box" "B/bitty-box.html")
    ("bixie" "B/bixie.html")
    ("black art" "B/black-art.html")
    ("black hat" "B/black-hat.html")
    ("black hole" "B/black-hole.html")
    ("black magic" "B/black-magic.html")
    ("Black Screen of Death" "B/Black-Screen-of-Death.html")
    ("blammo" "B/blammo.html")
    ("blargh" "B/blargh.html")
    ("blast" "B/blast.html")
    ("blat" "B/blat.html")
    ("bletch" "B/bletch.html")
    ("bletcherous" "B/bletcherous.html")
    ("blinkenlights" "B/blinkenlights.html")
    ("blit" "B/blit.html")
    ("blitter" "B/blitter.html")
    ("blivet" "B/blivet.html")
    ("bloatware" "B/bloatware.html")
    ("BLOB" "B/BLOB.html")
    ("block" "B/block.html")
    ("blog" "B/blog.html")
    ("Bloggs Family" "B/Bloggs-Family.html")
    ("blogosphere" "B/blogosphere.html")
    ("blogrolling" "B/blogrolling.html")
    ("blow an EPROM" "B/blow-an-EPROM.html")
    ("blow away" "B/blow-away.html")
    ("blow out" "B/blow-out.html")
    ("blow past" "B/blow-past.html")
    ("blow up" "B/blow-up.html")
    ("BLT" "B/BLT.html")
    ("blue box" "B/blue-box.html")
    ("Blue Glue" "B/Blue-Glue.html")
    ("blue goo" "B/blue-goo.html")
    ("Blue Screen of Death" "B/Blue-Screen-of-Death.html")
    ("blue wire" "B/blue-wire.html")
    ("blurgle" "B/blurgle.html")
    ("BNF" "B/BNF.html")
    ("boa" "B/boa.html")
    ("board" "B/board.html")
    ("boat anchor" "B/boat-anchor.html")
    ("bob" "B/bob.html")
    ("bodge" "B/bodge.html")
    ("BOF" "B/BOF.html")
    ("BOFH" "B/BOFH.html")
    ("bogo-sort" "B/bogo-sort.html")
    ("bogometer" "B/bogometer.html")
    ("BogoMIPS" "B/BogoMIPS.html")
    ("bogon" "B/bogon.html")
    ("bogon filter" "B/bogon-filter.html")
    ("bogon flux" "B/bogon-flux.html")
    ("bogosity" "B/bogosity.html")
    ("bogotify" "B/bogotify.html")
    ("bogue out" "B/bogue-out.html")
    ("bogus" "B/bogus.html")
    ("Bohr bug" "B/Bohr-bug.html")
    ("boink" "B/boink.html")
    ("bomb" "B/bomb.html")
    ("bondage-and-discipline language" "B/bondage-and-discipline-language.html")
    ("bonk/oif" "B/bonk-oif.html")
    ("book titles" "B/book-titles.html")
    ("boot" "B/boot.html")
    ("Borg" "B/Borg.html")
    ("borken" "B/borken.html")
    ("bot" "B/bot.html")
    ("bottom feeder" "B/bottom-feeder.html")
    ("bottom-post" "B/bottom-post.html")
    ("bottom-up implementation" "B/bottom-up-implementation.html")
    ("bounce" "B/bounce.html")
    ("bounce message" "B/bounce-message.html")
    ("boustrophedon" "B/boustrophedon.html")
    ("box" "B/box.html")
    ("boxed comments" "B/boxed-comments.html")
    ("boxen" "B/boxen.html")
    ("boxology" "B/boxology.html")
    ("bozotic" "B/bozotic.html")
    ("brain dump" "B/brain-dump.html")
    ("brain fart" "B/brain-fart.html")
    ("brain-damaged" "B/brain-damaged.html")
    ("brain-dead" "B/brain-dead.html")
    ("braino" "B/braino.html")
    ("brainwidth" "B/brainwidth.html")
    ("bread crumbs" "B/bread-crumbs.html")
    ("break" "B/break.html")
    ("break-even point" "B/break-even-point.html")
    ("breath-of-life packet" "B/breath-of-life-packet.html")
    ("breedle" "B/breedle.html")
    ("Breidbart Index" "B/Breidbart-Index.html")
    ("bricktext" "B/bricktext.html")
    ("bring X to its knees" "B/bring-X-to-its-knees.html")
    ("brittle" "B/brittle.html")
    ("broadcast storm" "B/broadcast-storm.html")
    ("broken" "B/broken.html")
    ("broken arrow" "B/broken-arrow.html")
    ("broken-ring network" "B/broken-ring-network.html")
    ("BrokenWindows" "B/BrokenWindows.html")
    ("broket" "B/broket.html")
    ("Brooks's Law" "B/Brookss-Law.html")
    ("brown-paper-bag bug" "B/brown-paper-bag-bug.html")
    ("browser" "B/browser.html")
    ("BRS" "B/BRS.html")
    ("brute force" "B/brute-force.html")
    ("brute force and ignorance" "B/brute-force-and-ignorance.html")
    ("BSD" "B/BSD.html")
    ("BSOD" "B/BSOD.html")
    ("BUAF" "B/BUAF.html")
    ("BUAG" "B/BUAG.html")
    ("bubble sort" "B/bubble-sort.html")
    ("bucky bits" "B/bucky-bits.html")
    ("buffer chuck" "B/buffer-chuck.html")
    ("buffer overflow" "B/buffer-overflow.html")
    ("bug" "B/bug.html")
    ("bug-compatible" "B/bug-compatible.html")
    ("bug-for-bug compatible" "B/bug-for-bug-compatible.html")
    ("bug-of-the-month club" "B/bug-of-the-month-club.html")
    ("bulletproof" "B/bulletproof.html")
    ("bullschildt" "B/bullschildt.html")
    ("bump" "B/bump.html")
    ("burble" "B/burble.html")
    ("buried treasure" "B/buried-treasure.html")
    ("burn a CD" "B/burn-a-CD.html")
    ("burn-in period" "B/burn-in-period.html")
    ("burst page" "B/burst-page.html")
    ("busy-wait" "B/busy-wait.html")
    ("buzz" "B/buzz.html")
    ("buzzword-compliant" "B/buzzword-compliant.html")
    ("BWQ" "B/BWQ.html")
    ("by hand" "B/by-hand.html")
    ("byte" "B/byte.html")
    ("byte sex" "B/byte-sex.html")
    ("bytesexual" "B/bytesexual.html")
    ("Bzzzt! Wrong." "B/Bzzzt-Wrong.html")
    ("C" "C/C.html")
    ("C Programmer's Disease" "C/C-Programmers-Disease.html")
    ("C&amp;C" "C/C-ampersand-C.html")
    ("C++" "C/C-plus-plus.html")
    ("calculator" "C/calculator.html")
    ("Camel Book" "C/Camel-Book.html")
    ("camelCase" "C/camelCase.html")
    ("camelCasing" "C/camelCasing.html")
    ("can't happen" "C/can-t-happen.html")
    ("cancelbot" "C/cancelbot.html")
    ("Cancelmoose[tm]" "C/Cancelmoose.html")
    ("candygrammar" "C/candygrammar.html")
    ("canonical" "C/canonical.html")
    ("careware" "C/careware.html")
    ("cargo cult programming" "C/cargo-cult-programming.html")
    ("cascade" "C/cascade.html")
    ("case and paste" "C/case-and-paste.html")
    ("case mod" "C/case-mod.html")
    ("casters-up mode" "C/casters-up-mode.html")
    ("casting the runes" "C/casting-the-runes.html")
    ("cat" "C/cat.html")
    ("catatonic" "C/catatonic.html")
    ("cathedral" "C/cathedral.html")
    ("cd tilde" "C/cd-tilde.html")
    ("CDA" "C/CDA.html")
    ("cdr" "C/cdr.html")
    ("chad" "C/chad.html")
    ("chad box" "C/chad-box.html")
    ("chain" "C/chain.html")
    ("chainik" "C/chainik.html")
    ("channel" "C/channel.html")
    ("channel hopping" "C/channel-hopping.html")
    ("channel op" "C/channel-op.html")
    ("chanop" "C/chanop.html")
    ("char" "C/char.html")
    ("charityware" "C/charityware.html")
    ("chase pointers" "C/chase-pointers.html")
    ("chawmp" "C/chawmp.html")
    ("check" "C/check.html")
    ("cheerfully" "C/cheerfully.html")
    ("chemist" "C/chemist.html")
    ("Chernobyl chicken" "C/Chernobyl-chicken.html")
    ("Chernobyl packet" "C/Chernobyl-packet.html")
    ("chicken head" "C/chicken-head.html")
    ("chickenboner" "C/chickenboner.html")
    ("chiclet keyboard" "C/chiclet-keyboard.html")
    ("Chinese Army technique" "C/Chinese-Army-technique.html")
    ("choad" "C/choad.html")
    ("choke" "C/choke.html")
    ("chomp" "C/chomp.html")
    ("chomper" "C/chomper.html")
    ("CHOP" "C/CHOP.html")
    ("Christmas tree" "C/Christmas-tree.html")
    ("Christmas tree packet" "C/Christmas-tree-packet.html")
    ("chrome" "C/chrome.html")
    ("chug" "C/chug.html")
    ("Church of the SubGenius" "C/Church-of-the-SubGenius.html")
    ("CI$" "C/CIS.html")
    ("Cinderella Book" "C/Cinderella-Book.html")
    ("Classic C" "C/Classic-C.html")
    ("clean" "C/clean.html")
    ("click of death" "C/click-of-death.html")
    ("CLM" "C/CLM.html")
    ("clobber" "C/clobber.html")
    ("clock" "C/clock.html")
    ("clocks" "C/clocks.html")
    ("clone" "C/clone.html")
    ("clone-and-hack coding" "C/clone-and-hack-coding.html")
    ("clover key" "C/clover-key.html")
    ("clue-by-four" "C/clue-by-four.html")
    ("clustergeeking" "C/clustergeeking.html")
    ("co-lo" "C/co-lo.html")
    ("coaster" "C/coaster.html")
    ("coaster toaster" "C/coaster-toaster.html")
    ("COBOL" "C/COBOL.html")
    ("COBOL fingers" "C/COBOL-fingers.html")
    ("cobweb site" "C/cobweb-site.html")
    ("code" "C/code.html")
    ("code grinder" "C/code-grinder.html")
    ("code monkey" "C/code-monkey.html")
    ("Code of the Geeks" "C/Code-of-the-Geeks.html")
    ("code police" "C/code-police.html")
    ("codes" "C/codes.html")
    ("codewalker" "C/codewalker.html")
    ("coefficient of X" "C/coefficient-of-X.html")
    ("cokebottle" "C/cokebottle.html")
    ("cold boot" "C/cold-boot.html")
    ("COME FROM" "C/COME-FROM.html")
    ("comm mode" "C/comm-mode.html")
    ("command key" "C/command-key.html")
    ("comment out" "C/comment-out.html")
    ("Commonwealth Hackish" "C/Commonwealth-Hackish.html")
    ("compact" "C/compact.html")
    ("compiler jock" "C/compiler-jock.html")
    ("compo" "C/compo.html")
    ("compress" "C/compress.html")
    ("Compu$erve" "C/CompuServe.html")
    ("computer confetti" "C/computer-confetti.html")
    ("computron" "C/computron.html")
    ("con" "C/con_.html")
    ("condition out" "C/condition-out.html")
    ("condom" "C/condom.html")
    ("confuser" "C/confuser.html")
    ("connector conspiracy" "C/connector-conspiracy.html")
    ("cons" "C/cons.html")
    ("considered harmful" "C/considered-harmful.html")
    ("console" "C/console.html")
    ("console jockey" "C/console-jockey.html")
    ("content-free" "C/content-free.html")
    ("control-C" "C/control-C.html")
    ("control-O" "C/control-O.html")
    ("control-Q" "C/control-Q.html")
    ("control-S" "C/control-S.html")
    ("Conway's Law" "C/Conways-Law.html")
    ("cookbook" "C/cookbook.html")
    ("cooked mode" "C/cooked-mode.html")
    ("cookie" "C/cookie.html")
    ("cookie bear" "C/cookie-bear.html")
    ("cookie file" "C/cookie-file.html")
    ("cookie jar" "C/cookie-jar.html")
    ("cookie monster" "C/cookie-monster.html")
    ("copious free time" "C/copious-free-time.html")
    ("copper" "C/copper.html")
    ("copy protection" "C/copy-protection.html")
    ("copybroke" "C/copybroke.html")
    ("copycenter" "C/copycenter.html")
    ("copyleft" "C/copyleft.html")
    ("copyparty" "C/copyparty.html")
    ("copywronged" "C/copywronged.html")
    ("core" "C/core.html")
    ("core cancer" "C/core-cancer.html")
    ("core dump" "C/core-dump.html")
    ("core leak" "C/core-leak.html")
    ("Core Wars" "C/Core-Wars.html")
    ("cosmic rays" "C/cosmic-rays.html")
    ("cough and die" "C/cough-and-die.html")
    ("courier" "C/courier.html")
    ("cow orker" "C/cow-orker.html")
    ("cowboy" "C/cowboy.html")
    ("CP/M" "C/CP-M.html")
    ("CPU Wars" "C/CPU-Wars.html")
    ("crack" "C/crack.html")
    ("crack root" "C/crack-root.html")
    ("cracker" "C/cracker.html")
    ("cracking" "C/cracking.html")
    ("crank" "C/crank.html")
    ("crapplet" "C/crapplet.html")
    ("CrApTeX" "C/CrApTeX.html")
    ("crash" "C/crash.html")
    ("crash and burn" "C/crash-and-burn.html")
    ("crawling horror" "C/crawling-horror.html")
    ("CRC handbook" "C/CRC-handbook.html")
    ("creationism" "C/creationism.html")
    ("creep" "C/creep.html")
    ("creeping elegance" "C/creeping-elegance.html")
    ("creeping featurism" "C/creeping-featurism.html")
    ("creeping featuritis" "C/creeping-featuritis.html")
    ("cretin" "C/cretin.html")
    ("cretinous" "C/cretinous.html")
    ("crippleware" "C/crippleware.html")
    ("critical mass" "C/critical-mass.html")
    ("crlf" "C/crlf.html")
    ("crock" "C/crock.html")
    ("cross-post" "C/cross-post.html")
    ("crossload" "C/crossload.html")
    ("crudware" "C/crudware.html")
    ("cruft" "C/cruft.html")
    ("cruft together" "C/cruft-together.html")
    ("cruftsmanship" "C/cruftsmanship.html")
    ("crufty" "C/crufty.html")
    ("crumb" "C/crumb.html")
    ("crunch" "C/crunch.html")
    ("cryppie" "C/cryppie.html")
    ("cthulhic" "C/cthulhic.html")
    ("CTSS" "C/CTSS.html")
    ("cube" "C/cube.html")
    ("cup holder" "C/cup-holder.html")
    ("cursor dipped in X" "C/cursor-dipped-in-X.html")
    ("cuspy" "C/cuspy.html")
    ("cut a tape" "C/cut-a-tape.html")
    ("cybercrud" "C/cybercrud.html")
    ("cyberpunk" "C/cyberpunk.html")
    ("cyberspace" "C/cyberspace.html")
    ("cycle" "C/cycle.html")
    ("cycle of reincarnation" "C/cycle-of-reincarnation.html")
    ("cycle server" "C/cycle-server.html")
    ("cypherpunk" "C/cypherpunk.html")
    ("C|N&gt;K" "C/CNK.html")
    ("daemon" "D/daemon.html")
    ("daemon book" "D/daemon-book.html")
    ("dahmum" "D/dahmum.html")
    ("dancing frog" "D/dancing-frog.html")
    ("dangling pointer" "D/dangling-pointer.html")
    ("dark-side hacker" "D/dark-side-hacker.html")
    ("Datamation" "D/Datamation.html")
    ("DAU" "D/DAU.html")
    ("Dave the Resurrector" "D/Dave-the-Resurrector.html")
    ("day mode" "D/day-mode.html")
    ("dd" "D/dd.html")
    ("DDT" "D/DDT.html")
    ("de-rezz" "D/de-rezz.html")
    ("dead" "D/dead.html")
    ("dead beef attack" "D/dead-beef-attack.html")
    ("dead code" "D/dead-code.html")
    ("dead-tree version" "D/dead-tree-version.html")
    ("DEADBEEF" "D/DEADBEEF.html")
    ("deadlock" "D/deadlock.html")
    ("deadly embrace" "D/deadly-embrace.html")
    ("death code" "D/death-code.html")
    ("Death Square" "D/Death-Square.html")
    ("Death Star" "D/Death-Star.html")
    ("Death, X of" "D/Death--X-of.html")
    ("DEC" "D/DEC.html")
    ("DEC Wars" "D/DEC-Wars.html")
    ("decay" "D/decay.html")
    ("deckle" "D/deckle.html")
    ("DED" "D/DED.html")
    ("deep hack mode" "D/deep-hack-mode.html")
    ("deep magic" "D/deep-magic.html")
    ("deep space" "D/deep-space.html")
    ("defenestration" "D/defenestration.html")
    ("defined as" "D/defined-as.html")
    ("deflicted" "D/deflicted.html")
    ("dehose" "D/dehose.html")
    ("Dejagoo" "D/Dejagoo.html")
    ("deletia" "D/deletia.html")
    ("deliminator" "D/deliminator.html")
    ("delint" "D/delint.html")
    ("delta" "D/delta.html")
    ("demented" "D/demented.html")
    ("demigod" "D/demigod.html")
    ("demo" "D/demo.html")
    ("demo mode" "D/demo-mode.html")
    ("demoeffect" "D/demoeffect.html")
    ("demogroup" "D/demogroup.html")
    ("demon" "D/demon.html")
    ("demon dialer" "D/demon-dialer.html")
    ("demoparty" "D/demoparty.html")
    ("demoscene" "D/demoscene.html")
    ("dentro" "D/dentro.html")
    ("depeditate" "D/depeditate.html")
    ("deprecated" "D/deprecated.html")
    ("derf" "D/derf.html")
    ("deserves to lose" "D/deserves-to-lose.html")
    ("despew" "D/despew.html")
    ("dickless workstation" "D/dickless-workstation.html")
    ("dictionary flame" "D/dictionary-flame.html")
    ("diddle" "D/diddle.html")
    ("die" "D/die.html")
    ("die horribly" "D/die-horribly.html")
    ("diff" "D/diff.html")
    ("dike" "D/dike.html")
    ("Dilbert" "D/Dilbert.html")
    ("ding" "D/ding.html")
    ("dink" "D/dink.html")
    ("dinosaur" "D/dinosaur.html")
    ("dinosaur pen" "D/dinosaur-pen.html")
    ("dinosaurs mating" "D/dinosaurs-mating.html")
    ("dirtball" "D/dirtball.html")
    ("dirty power" "D/dirty-power.html")
    ("disclaimer" "D/disclaimer.html")
    ("Discordianism" "D/Discordianism.html")
    ("disemvowel" "D/disemvowel.html")
    ("disk farm" "D/disk-farm.html")
    ("display hack" "D/display-hack.html")
    ("dispress" "D/dispress.html")
    ("Dissociated Press" "D/Dissociated-Press.html")
    ("distribution" "D/distribution.html")
    ("distro" "D/distro.html")
    ("disusered" "D/disusered.html")
    ("DMZ" "D/DMZ.html")
    ("do protocol" "D/do-protocol.html")
    ("doc" "D/doc.html")
    ("documentation" "D/documentation.html")
    ("dodgy" "D/dodgy.html")
    ("dogcow" "D/dogcow.html")
    ("dogfood" "D/dogfood.html")
    ("dogpile" "D/dogpile.html")
    ("dogwash" "D/dogwash.html")
    ("Don't do that then!" "D/Don-t-do-that-then-.html")
    ("dongle" "D/dongle.html")
    ("dongle-disk" "D/dongle-disk.html")
    ("Doom, X of" "D/Doom--X-of.html")
    ("doorstop" "D/doorstop.html")
    ("DoS attack" "D/DoS-attack.html")
    ("dot file" "D/dot-file.html")
    ("double bucky" "D/double-bucky.html")
    ("doubled sig" "D/doubled-sig.html")
    ("down" "D/down.html")
    ("download" "D/download.html")
    ("DP" "D/DP.html")
    ("DPer" "D/DPer.html")
    ("Dr. Fred Mbogo" "D/Dr--Fred-Mbogo.html")
    ("dragon" "D/dragon.html")
    ("Dragon Book" "D/Dragon-Book.html")
    ("drain" "D/drain.html")
    ("dread high-bit disease" "D/dread-high-bit-disease.html")
    ("dread questionmark disease" "D/dread-questionmark-disease.html")
    ("DRECNET" "D/DRECNET.html")
    ("driver" "D/driver.html")
    ("droid" "D/droid.html")
    ("drone" "D/drone.html")
    ("drool-proof paper" "D/drool-proof-paper.html")
    ("drop on the floor" "D/drop-on-the-floor.html")
    ("drop-ins" "D/drop-ins.html")
    ("drop-outs" "D/drop-outs.html")
    ("drugged" "D/drugged.html")
    ("drum" "D/drum.html")
    ("drunk mouse syndrome" "D/drunk-mouse-syndrome.html")
    ("DSW" "D/DSW.html")
    ("dub dub dub" "D/dub-dub-dub.html")
    ("Duff's device" "D/Duffs-device.html")
    ("dumb terminal" "D/dumb-terminal.html")
    ("dumbass attack" "D/dumbass-attack.html")
    ("dumbed down" "D/dumbed-down.html")
    ("dump" "D/dump.html")
    ("dumpster diving" "D/dumpster-diving.html")
    ("dusty deck" "D/dusty-deck.html")
    ("DWIM" "D/DWIM.html")
    ("dynner" "D/dynner.html")
    ("Easter egg" "E/Easter-egg.html")
    ("Easter egging" "E/Easter-egging.html")
    ("eat flaming death" "E/eat-flaming-death.html")
    ("EBCDIC" "E/EBCDIC.html")
    ("ECP" "E/ECP.html")
    ("ed" "E/ed.html")
    ("egg" "E/egg.html")
    ("egosurf" "E/egosurf.html")
    ("eighty-column mind" "E/eighty-column-mind.html")
    ("El Camino Bignum" "E/El-Camino-Bignum.html")
    ("elder days" "E/elder-days.html")
    ("elegant" "E/elegant.html")
    ("elephantine" "E/elephantine.html")
    ("elevator controller" "E/elevator-controller.html")
    ("elite" "E/elite.html")
    ("ELIZA effect" "E/ELIZA-effect.html")
    ("elvish" "E/elvish.html")
    ("EMACS" "E/EMACS.html")
    ("email" "E/email.html")
    ("emoticon" "E/emoticon.html")
    ("EMP" "E/EMP.html")
    ("empire" "E/empire.html")
    ("engine" "E/engine.html")
    ("English" "E/English.html")
    ("enhancement" "E/enhancement.html")
    ("ENQ" "E/ENQ.html")
    ("EOD" "E/EOD.html")
    ("EOF" "E/EOF.html")
    ("EOL" "E/EOL.html")
    ("EOU" "E/EOU.html")
    ("epoch" "E/epoch.html")
    ("epsilon" "E/epsilon.html")
    ("epsilon squared" "E/epsilon-squared.html")
    ("era" "E/era.html")
    ("Eric Conspiracy" "E/Eric-Conspiracy.html")
    ("Eris" "E/Eris.html")
    ("erotics" "E/erotics.html")
    ("error 33" "E/error-33.html")
    ("eurodemo" "E/eurodemo.html")
    ("evil" "E/evil.html")
    ("evil and rude" "E/evil-and-rude.html")
    ("Evil Empire" "E/Evil-Empire.html")
    ("exa-" "E/exa-.html")
    ("examining the entrails" "E/examining-the-entrails.html")
    ("EXCH" "E/EXCH.html")
    ("excl" "E/excl.html")
    ("EXE" "E/EXE.html")
    ("exec" "E/exec.html")
    ("exercise, left as an" "E/exercise--left-as-an.html")
    ("Exon" "E/Exon.html")
    ("Exploder" "E/Exploder.html")
    ("exploit" "E/exploit.html")
    ("external memory" "E/external-memory.html")
    ("eye candy" "E/eye-candy.html")
    ("eyeball search" "E/eyeball-search.html")
    ("face time" "F/face-time.html")
    ("factor" "F/factor.html")
    ("fairings" "F/fairings.html")
    ("fall over" "F/fall-over.html")
    ("fall through" "F/fall-through.html")
    ("fan" "F/fan.html")
    ("fandango on core" "F/fandango-on-core.html")
    ("FAQ" "F/FAQ.html")
    ("FAQ list" "F/FAQ-list.html")
    ("FAQL" "F/FAQL.html")
    ("faradize" "F/faradize.html")
    ("farkled" "F/farkled.html")
    ("farm" "F/farm.html")
    ("fascist" "F/fascist.html")
    ("fat electrons" "F/fat-electrons.html")
    ("fat pipe" "F/fat-pipe.html")
    ("fat-finger" "F/fat-finger.html")
    ("faulty" "F/faulty.html")
    ("fear and loathing" "F/fear-and-loathing.html")
    ("feature" "F/feature.html")
    ("feature creature" "F/feature-creature.html")
    ("feature creep" "F/feature-creep.html")
    ("feature key" "F/feature-key.html")
    ("feature shock" "F/feature-shock.html")
    ("featurectomy" "F/featurectomy.html")
    ("feep" "F/feep.html")
    ("feeper" "F/feeper.html")
    ("feeping creature" "F/feeping-creature.html")
    ("feeping creaturism" "F/feeping-creaturism.html")
    ("feetch feetch" "F/feetch-feetch.html")
    ("fence" "F/fence.html")
    ("fencepost error" "F/fencepost-error.html")
    ("fiber-seeking backhoe" "F/fiber-seeking-backhoe.html")
    ("FidoNet" "F/FidoNet.html")
    ("field circus" "F/field-circus.html")
    ("field servoid" "F/field-servoid.html")
    ("file signature" "F/file-signature.html")
    ("filk" "F/filk.html")
    ("film at 11" "F/film-at-11.html")
    ("filter" "F/filter.html")
    ("Finagle's Law" "F/Finagles-Law.html")
    ("fine" "F/fine.html")
    ("finger" "F/finger.html")
    ("finger trouble" "F/finger-trouble.html")
    ("finger-pointing syndrome" "F/finger-pointing-syndrome.html")
    ("finn" "F/finn.html")
    ("firebottle" "F/firebottle.html")
    ("firefighting" "F/firefighting.html")
    ("firehose syndrome" "F/firehose-syndrome.html")
    ("firewall code" "F/firewall-code.html")
    ("firewall machine" "F/firewall-machine.html")
    ("fireworks mode" "F/fireworks-mode.html")
    ("firmware" "F/firmware.html")
    ("fish" "F/fish.html")
    ("FISH queue" "F/FISH-queue.html")
    ("fisking" "F/fisking.html")
    ("FITNR" "F/FITNR.html")
    ("fix" "F/fix.html")
    ("FIXME" "F/FIXME.html")
    ("flag" "F/flag.html")
    ("flag day" "F/flag-day.html")
    ("flaky" "F/flaky.html")
    ("flamage" "F/flamage.html")
    ("flame" "F/flame.html")
    ("flame bait" "F/flame-bait.html")
    ("flame on" "F/flame-on.html")
    ("flame war" "F/flame-war.html")
    ("flamer" "F/flamer.html")
    ("flap" "F/flap.html")
    ("flarp" "F/flarp.html")
    ("flash crowd" "F/flash-crowd.html")
    ("flat" "F/flat.html")
    ("flat-ASCII" "F/flat-ASCII.html")
    ("flat-file" "F/flat-file.html")
    ("flatten" "F/flatten.html")
    ("flavor" "F/flavor.html")
    ("flavorful" "F/flavorful.html")
    ("flippy" "F/flippy.html")
    ("flood" "F/flood.html")
    ("flowchart" "F/flowchart.html")
    ("flower key" "F/flower-key.html")
    ("flush" "F/flush.html")
    ("flypage" "F/flypage.html")
    ("Flyspeck 3" "F/Flyspeck-3.html")
    ("flytrap" "F/flytrap.html")
    ("FM" "F/FM.html")
    ("fnord" "F/fnord.html")
    ("FOAF" "F/FOAF.html")
    ("FOD" "F/FOD.html")
    ("fold case" "F/fold-case.html")
    ("followup" "F/followup.html")
    ("fontology" "F/fontology.html")
    ("foo" "F/foo.html")
    ("foobar" "F/foobar.html")
    ("fool" "F/fool.html")
    ("fool file" "F/fool-file.html")
    ("Foonly" "F/Foonly.html")
    ("footprint" "F/footprint.html")
    ("for free" "F/for-free.html")
    ("for the rest of us" "F/for-the-rest-of-us.html")
    ("for values of" "F/for-values-of.html")
    ("fora" "F/fora.html")
    ("foreground" "F/foreground.html")
    ("fork" "F/fork.html")
    ("fork bomb" "F/fork-bomb.html")
    ("forked" "F/forked.html")
    ("Formosa's Law" "F/Formosas-Law.html")
    ("Fortrash" "F/Fortrash.html")
    ("fortune cookie" "F/fortune-cookie.html")
    ("forum" "F/forum.html")
    ("fossil" "F/fossil.html")
    ("four-color glossies" "F/four-color-glossies.html")
    ("frag" "F/frag.html")
    ("fragile" "F/fragile.html")
    ("Frankenputer" "F/Frankenputer.html")
    ("fred" "F/fred.html")
    ("Fred Foobar" "F/Fred-Foobar.html")
    ("frednet" "F/frednet.html")
    ("free software" "F/free-software.html")
    ("freeware" "F/freeware.html")
    ("freeze" "F/freeze.html")
    ("fried" "F/fried.html")
    ("frink" "F/frink.html")
    ("friode" "F/friode.html")
    ("fritterware" "F/fritterware.html")
    ("frob" "F/frob.html")
    ("frobnicate" "F/frobnicate.html")
    ("frobnitz" "F/frobnitz.html")
    ("frog" "F/frog.html")
    ("frogging" "F/frogging.html")
    ("front end" "F/front-end.html")
    ("frotz" "F/frotz.html")
    ("frotzed" "F/frotzed.html")
    ("frowney" "F/frowney.html")
    ("FRS" "F/FRS.html")
    ("fry" "F/fry.html")
    ("fscking" "F/fscking.html")
    ("FSF" "F/FSF.html")
    ("-fu" "F/suffix-fu.html")
    ("FUBAR" "F/FUBAR.html")
    ("fuck me harder" "F/fuck-me-harder.html")
    ("FUD" "F/FUD.html")
    ("FUD wars" "F/FUD-wars.html")
    ("fudge" "F/fudge.html")
    ("fudge factor" "F/fudge-factor.html")
    ("fuel up" "F/fuel-up.html")
    ("Full Monty" "F/Full-Monty.html")
    ("fum" "F/fum.html")
    ("functino" "F/functino.html")
    ("funky" "F/funky.html")
    ("funny money" "F/funny-money.html")
    ("furrfu" "F/furrfu.html")
    ("G" "G/G.html")
    ("gang bang" "G/gang-bang.html")
    ("Gang of Four" "G/Gang-of-Four.html")
    ("garbage collect" "G/garbage-collect.html")
    ("garply" "G/garply.html")
    ("gas" "G/gas.html")
    ("Gates's Law" "G/Gatess-Law.html")
    ("gawble" "G/gawble.html")
    ("GC" "G/GC.html")
    ("GCOS" "G/GCOS.html")
    ("GECOS" "G/GECOS.html")
    ("gedanken" "G/gedanken.html")
    ("geef" "G/geef.html")
    ("geek" "G/geek.html")
    ("geek code" "G/geek-code.html")
    ("geek out" "G/geek-out.html")
    ("geekasm" "G/geekasm.html")
    ("gen" "G/gen.html")
    ("gender mender" "G/gender-mender.html")
    ("General Public Virus" "G/General-Public-Virus.html")
    ("generate" "G/generate.html")
    ("Genius From Mars Technique" "G/Genius-From-Mars-Technique.html")
    ("gensym" "G/gensym.html")
    ("Get a life!" "G/Get-a-life-.html")
    ("Get a real computer!" "G/Get-a-real-computer-.html")
    ("GandhiCon" "G/GandhiCon.html")
    ("gib" "G/gib.html")
    ("GIFs at 11" "G/GIFs-at-11.html")
    ("gig" "G/gig.html")
    ("giga-" "G/giga-.html")
    ("GIGO" "G/GIGO.html")
    ("gilley" "G/gilley.html")
    ("gillion" "G/gillion.html")
    ("ginger" "G/ginger.html")
    ("GIPS" "G/GIPS.html")
    ("GIYF" "G/GIYF.html")
    ("glark" "G/glark.html")
    ("glass" "G/glass.html")
    ("glass tty" "G/glass-tty.html")
    ("glassfet" "G/glassfet.html")
    ("glitch" "G/glitch.html")
    ("glob" "G/glob.html")
    ("glork" "G/glork.html")
    ("glue" "G/glue.html")
    ("gnarly" "G/gnarly.html")
    ("GNU" "G/GNU.html")
    ("gnubie" "G/gnubie.html")
    ("GNUMACS" "G/GNUMACS.html")
    ("go flatline" "G/go-flatline.html")
    ("go gold" "G/go-gold.html")
    ("go root" "G/go-root.html")
    ("go-faster stripes" "G/go-faster-stripes.html")
    ("GoAT" "G/GoAT.html")
    ("goat file" "G/goat-file.html")
    ("gobble" "G/gobble.html")
    ("Godwin's Law" "G/Godwins-Law.html")
    ("Godzillagram" "G/Godzillagram.html")
    ("golden" "G/golden.html")
    ("golf-ball printer" "G/golf-ball-printer.html")
    ("gonk" "G/gonk.html")
    ("gonkulator" "G/gonkulator.html")
    ("gonzo" "G/gonzo.html")
    ("Good Thing" "G/Good-Thing.html")
    ("google" "G/google.html")
    ("google juice" "G/google-juice.html")
    ("gopher" "G/gopher.html")
    ("gopher hole" "G/gopher-hole.html")
    ("gorets" "G/gorets.html")
    ("gorilla arm" "G/gorilla-arm.html")
    ("gorp" "G/gorp.html")
    ("GOSMACS" "G/GOSMACS.html")
    ("gotcha" "G/gotcha.html")
    ("GPL" "G/GPL.html")
    ("GPV" "G/GPV.html")
    ("gray goo" "G/gray-goo.html")
    ("gray hat" "G/gray-hat.html")
    ("Great Internet Explosion" "G/Great-Internet-Explosion.html")
    ("Great Renaming" "G/Great-Renaming.html")
    ("Great Runes" "G/Great-Runes.html")
    ("Great Worm" "G/Great-Worm.html")
    ("great-wall" "G/great-wall.html")
    ("green bytes" "G/green-bytes.html")
    ("green card" "G/green-card.html")
    ("green lightning" "G/green-lightning.html")
    ("green machine" "G/green-machine.html")
    ("Green's Theorem" "G/Greens-Theorem.html")
    ("greenbar" "G/greenbar.html")
    ("grep" "G/grep.html")
    ("gribble" "G/gribble.html")
    ("grilf" "G/grilf.html")
    ("grind" "G/grind.html")
    ("grind crank" "G/grind-crank.html")
    ("gritch" "G/gritch.html")
    ("grok" "G/grok.html")
    ("gronk" "G/gronk.html")
    ("gronk out" "G/gronk-out.html")
    ("gronked" "G/gronked.html")
    ("grovel" "G/grovel.html")
    ("grue" "G/grue.html")
    ("grunge" "G/grunge.html")
    ("gubbish" "G/gubbish.html")
    ("Guido" "G/Guido.html")
    ("guiltware" "G/guiltware.html")
    ("gumby" "G/gumby.html")
    ("gunch" "G/gunch.html")
    ("gunpowder chicken" "G/gunpowder-chicken.html")
    ("guru" "G/guru.html")
    ("guru meditation" "G/guru-meditation.html")
    ("gweep" "G/gweep.html")
    ("h" "H/h.html")
    ("ha ha only serious" "H/ha-ha-only-serious.html")
    ("hack" "H/hack.html")
    ("hack attack" "H/hack-attack.html")
    ("hack mode" "H/hack-mode.html")
    ("hack on" "H/hack-on.html")
    ("hack together" "H/hack-together.html")
    ("hack up" "H/hack-up.html")
    ("hack value" "H/hack-value.html")
    ("hacked off" "H/hacked-off.html")
    ("hacked up" "H/hacked-up.html")
    ("hacker" "H/hacker.html")
    ("hacker ethic" "H/hacker-ethic.html")
    ("hacker humor" "H/hacker-humor.html")
    ("Hackers (the movie)" "H/Hackers-the-movie.html")
    ("hacking run" "H/hacking-run.html")
    ("Hacking X for Y" "H/Hacking-X-for-Y.html")
    ("Hackintosh" "H/Hackintosh.html")
    ("hackish" "H/hackish.html")
    ("hackishness" "H/hackishness.html")
    ("hackitude" "H/hackitude.html")
    ("hair" "H/hair.html")
    ("hairball" "H/hairball.html")
    ("hairy" "H/hairy.html")
    ("HAKMEM" "H/HAKMEM.html")
    ("hakspek" "H/hakspek.html")
    ("Halloween Documents" "H/Halloween-Documents.html")
    ("ham" "H/ham.html")
    ("hammer" "H/hammer.html")
    ("hamster" "H/hamster.html")
    ("HAND" "H/HAND.html")
    ("hand cruft" "H/hand-cruft.html")
    ("hand-hacking" "H/hand-hacking.html")
    ("hand-roll" "H/hand-roll.html")
    ("handle" "H/handle.html")
    ("handshaking" "H/handshaking.html")
    ("handwave" "H/handwave.html")
    ("hang" "H/hang.html")
    ("Hanlon's Razor" "H/Hanlons-Razor.html")
    ("happily" "H/happily.html")
    ("hard boot" "H/hard-boot.html")
    ("hardcoded" "H/hardcoded.html")
    ("hardwarily" "H/hardwarily.html")
    ("hardwired" "H/hardwired.html")
    ("has the X nature" "H/has-the-X-nature.html")
    ("hash bucket" "H/hash-bucket.html")
    ("hash collision" "H/hash-collision.html")
    ("hat" "H/hat.html")
    ("HCF" "H/HCF.html")
    ("heads down" "H/heads-down.html")
    ("heartbeat" "H/heartbeat.html")
    ("heatseeker" "H/heatseeker.html")
    ("heavy metal" "H/heavy-metal.html")
    ("heavy wizardry" "H/heavy-wizardry.html")
    ("heavyweight" "H/heavyweight.html")
    ("Hed Rat" "H/Hed-Rat.html")
    ("heisenbug" "H/heisenbug.html")
    ("hell desk" "H/hell-desk.html")
    ("hello sailor!" "H/hello-sailor-.html")
    ("hello world" "H/hello-world.html")
    ("hello, wall!" "H/hello--wall-.html")
    ("hex" "H/hex.html")
    ("hexadecimal" "H/hexadecimal.html")
    ("hexit" "H/hexit.html")
    ("HHOK" "H/HHOK.html")
    ("HHOS" "H/HHOS.html")
    ("hidden flag" "H/hidden-flag.html")
    ("high bit" "H/high-bit.html")
    ("high moby" "H/high-moby.html")
    ("highly" "H/highly.html")
    ("hing" "H/hing.html")
    ("hired gun" "H/hired-gun.html")
    ("hirsute" "H/hirsute.html")
    ("HLL" "H/HLL.html")
    ("hoarding" "H/hoarding.html")
    ("hog" "H/hog.html")
    ("hole" "H/hole.html")
    ("hollised" "H/hollised.html")
    ("holy penguin pee" "H/holy-penguin-pee.html")
    ("holy wars" "H/holy-wars.html")
    ("home box" "H/home-box.html")
    ("home machine" "H/home-machine.html")
    ("home page" "H/home-page.html")
    ("honey pot" "H/honey-pot.html")
    ("hook" "H/hook.html")
    ("hop" "H/hop.html")
    ("horked" "H/horked.html")
    ("hose" "H/hose.html")
    ("hosed" "H/hosed.html")
    ("hot chat" "H/hot-chat.html")
    ("hot spot" "H/hot-spot.html")
    ("hotlink" "H/hotlink.html")
    ("house wizard" "H/house-wizard.html")
    ("HP-SUX" "H/HP-SUX.html")
    ("HTH" "H/HTH.html")
    ("huff" "H/huff.html")
    ("hung" "H/hung.html")
    ("hungry puppy" "H/hungry-puppy.html")
    ("hungus" "H/hungus.html")
    ("hyperspace" "H/hyperspace.html")
    ("hysterical reasons" "H/hysterical-reasons.html")
    ("I didn't change anything!" "I/I-didn-t-change-anything-.html")
    ("I see no X here." "I/I-see-no-X-here-.html")
    ("IANAL" "I/IANAL.html")
    ("IBM" "I/IBM.html")
    ("ICBM address" "I/ICBM-address.html")
    ("ice" "I/ice.html")
    ("ID10T error" "I/idiot.html")
    ("idempotent" "I/idempotent.html")
    ("IDP" "I/IDP.html")
    ("If you want X, you know where to find it." "I/If-you-want-X--you-know-where-to-find-it-.html")
    ("ifdef out" "I/ifdef-out.html")
    ("IIRC" "I/IIRC.html")
    ("ill-behaved" "I/ill-behaved.html")
    ("IMHO" "I/IMHO.html")
    ("Imminent Death Of The Net Predicted!" "I/Imminent-Death-Of-The-Net-Predicted-.html")
    ("in the extreme" "I/in-the-extreme.html")
    ("incantation" "I/incantation.html")
    ("include" "I/include.html")
    ("include war" "I/include-war.html")
    ("indent style" "I/indent-style.html")
    ("Indent-o-Meter" "I/Indent-o-Meter.html")
    ("index of X" "I/index-of-X.html")
    ("infant mortality" "I/infant-mortality.html")
    ("infinite" "I/infinite.html")
    ("infinite loop" "I/infinite-loop.html")
    ("Infinite-Monkey Theorem" "I/Infinite-Monkey-Theorem.html")
    ("infinity" "I/infinity.html")
    ("inflate" "I/inflate.html")
    ("Infocom" "I/Infocom.html")
    ("initgame" "I/initgame.html")
    ("insanely great" "I/insanely-great.html")
    ("installfest" "I/installfest.html")
    ("INTERCAL" "I/INTERCAL.html")
    ("InterCaps" "I/InterCaps.html")
    ("interesting" "I/interesting.html")
    ("Internet" "I/Internet.html")
    ("Internet Death Penalty" "I/Internet-Death-Penalty.html")
    ("Internet Exploder" "I/Internet-Exploder.html")
    ("Internet Exploiter" "I/Internet-Exploiter.html")
    ("interrupt" "I/interrupt.html")
    ("interrupts locked out" "I/interrupts-locked-out.html")
    ("intertwingled" "I/intertwingled.html")
    ("intro" "I/intro.html")
    ("IRC" "I/IRC.html")
    ("iron" "I/iron.html")
    ("Iron Age" "I/Iron-Age.html")
    ("iron box" "I/iron-box.html")
    ("ironmonger" "I/ironmonger.html")
    ("ISO standard cup of tea" "I/ISO-standard-cup-of-tea.html")
    ("ISP" "I/ISP.html")
    ("ITS" "I/ITS.html")
    ("IWBNI" "I/IWBNI.html")
    ("IYFEG" "I/IYFEG.html")
    ("J. Random" "J/J--Random.html")
    ("J. Random Hacker" "J/J--Random-Hacker.html")
    ("jack in" "J/jack-in.html")
    ("jaggies" "J/jaggies.html")
    ("Java" "J/Java.html")
    ("JCL" "J/JCL.html")
    ("JEDR" "J/JEDR.html")
    ("Jeff K." "J/Jeff-K-.html")
    ("jello" "J/jello.html")
    ("Jeopardy-style quoting" "J/Jeopardy-style-quoting.html")
    ("jibble" "J/jibble.html")
    ("jiffy" "J/jiffy.html")
    ("job security" "J/job-security.html")
    ("jock" "J/jock.html")
    ("joe code" "J/joe-code.html")
    ("juggling eggs" "J/juggling-eggs.html")
    ("juice" "J/juice.html")
    ("jump off into never-never land" "J/jump-off-into-never-never-land.html")
    ("jupiter" "J/jupiter.html")
    ("K" "K/K.html")
    ("K&amp;R" "K/K-ampersand-R.html")
    ("k-" "K/k-.html")
    ("kahuna" "K/kahuna.html")
    ("kamikaze packet" "K/kamikaze-packet.html")
    ("kangaroo code" "K/kangaroo-code.html")
    ("ken" "K/ken.html")
    ("kernel-of-the-week club" "K/kernel-of-the-week-club.html")
    ("kgbvax" "K/kgbvax.html")
    ("KIBO" "K/KIBO.html")
    ("kiboze" "K/kiboze.html")
    ("kibozo" "K/kibozo.html")
    ("kick" "K/kick.html")
    ("kill file" "K/kill-file.html")
    ("killer app" "K/killer-app.html")
    ("killer micro" "K/killer-micro.html")
    ("killer poke" "K/killer-poke.html")
    ("kilo-" "K/kilo-.html")
    ("kilogoogle" "K/kilogoogle.html")
    ("KIPS" "K/KIPS.html")
    ("KISS Principle" "K/KISS-Principle.html")
    ("kit" "K/kit.html")
    ("KLB" "K/KLB.html")
    ("klone" "K/klone.html")
    ("kludge" "K/kludge.html")
    ("kluge" "K/kluge.html")
    ("kluge around" "K/kluge-around.html")
    ("kluge up" "K/kluge-up.html")
    ("Knights of the Lambda Calculus" "K/Knights-of-the-Lambda-Calculus.html")
    ("knobs" "K/knobs.html")
    ("Knuth" "K/Knuth.html")
    ("koan" "K/koan.html")
    ("kook" "K/kook.html")
    ("Kool-Aid" "K/Kool-Aid.html")
    ("kremvax" "K/kremvax.html")
    ("kyrka" "K/kyrka.html")
    ("lag" "L/lag.html")
    ("lamer" "L/lamer.html")
    ("LAN party" "L/LAN-party.html")
    ("language lawyer" "L/language-lawyer.html")
    ("languages of choice" "L/languages-of-choice.html")
    ("LART" "L/LART.html")
    ("larval stage" "L/larval-stage.html")
    ("lase" "L/lase.html")
    ("laser chicken" "L/laser-chicken.html")
    ("leaf site" "L/leaf-site.html")
    ("leak" "L/leak.html")
    ("leaky heap" "L/leaky-heap.html")
    ("leapfrog attack" "L/leapfrog-attack.html")
    ("leech" "L/leech.html")
    ("leech mode" "L/leech-mode.html")
    ("legal" "L/legal.html")
    ("legalese" "L/legalese.html")
    ("lenna" "L/lenna.html")
    ("LER" "L/LER.html")
    ("LERP" "L/LERP.html")
    ("let the smoke out" "L/let-the-smoke-out.html")
    ("letterbomb" "L/letterbomb.html")
    ("lexer" "L/lexer.html")
    ("life" "L/life.html")
    ("Life is hard" "L/Life-is-hard.html")
    ("light pipe" "L/light-pipe.html")
    ("lightweight" "L/lightweight.html")
    ("like kicking dead whales down the beach" "L/like-kicking-dead-whales-down-the-beach.html")
    ("like nailing jelly to a tree" "L/like-nailing-jelly-to-a-tree.html")
    ("line 666" "L/line-666.html")
    ("line eater, the" "L/line-eater--the.html")
    ("line noise" "L/line-noise.html")
    ("linearithmic" "L/linearithmic.html")
    ("link farm" "L/link-farm.html")
    ("link rot" "L/link-rot.html")
    ("link-dead" "L/link-dead.html")
    ("lint" "L/lint.html")
    ("Lintel" "L/Lintel.html")
    ("Linus" "L/Linus.html")
    ("Linux" "L/Linux.html")
    ("lion food" "L/lion-food.html")
    ("Lions Book" "L/Lions-Book.html")
    ("LISP" "L/LISP.html")
    ("list-bomb" "L/list-bomb.html")
    ("lithium lick" "L/lithium-lick.html")
    ("little-endian" "L/little-endian.html")
    ("live" "L/live.html")
    ("live data" "L/live-data.html")
    ("Live Free Or Die!" "L/Live-Free-Or-Die-.html")
    ("livelock" "L/livelock.html")
    ("liveware" "L/liveware.html")
    ("lobotomy" "L/lobotomy.html")
    ("locals, the" "L/locals--the.html")
    ("locked and loaded" "L/locked-and-loaded.html")
    ("locked up" "L/locked-up.html")
    ("logic bomb" "L/logic-bomb.html")
    ("logical" "L/logical.html")
    ("loop through" "L/loop-through.html")
    ("loose bytes" "L/loose-bytes.html")
    ("lord high fixer" "L/lord-high-fixer.html")
    ("lose" "L/lose.html")
    ("lose lose" "L/lose-lose.html")
    ("loser" "L/loser.html")
    ("losing" "L/losing.html")
    ("loss" "L/loss.html")
    ("lossage" "L/lossage.html")
    ("lossy" "L/lossy.html")
    ("lost in the noise" "L/lost-in-the-noise.html")
    ("lost in the underflow" "L/lost-in-the-underflow.html")
    ("lots of MIPS but no I/O" "L/lots-of-MIPS-but-no-I-O.html")
    ("low-bandwidth" "L/low-bandwidth.html")
    ("Lubarsky's Law of Cybernetic Entomology" "L/Lubarskys-Law-of-Cybernetic-Entomology.html")
    ("Lumber Cartel" "L/Lumber-Cartel.html")
    ("lunatic fringe" "L/lunatic-fringe.html")
    ("lurker" "L/lurker.html")
    ("luser" "L/luser.html")
    ("M" "M/M.html")
    ("M$" "M/MS.html")
    ("macdink" "M/macdink.html")
    ("machoflops" "M/machoflops.html")
    ("Macintoy" "M/Macintoy.html")
    ("Macintrash" "M/Macintrash.html")
    ("macro" "M/macro.html")
    ("macro-" "M/macro-.html")
    ("macrology" "M/macrology.html")
    ("maggotbox" "M/maggotbox.html")
    ("magic" "M/magic.html")
    ("magic cookie" "M/magic-cookie.html")
    ("magic number" "M/magic-number.html")
    ("magic smoke" "M/magic-smoke.html")
    ("mail storm" "M/mail-storm.html")
    ("mailbomb" "M/mailbomb.html")
    ("mailing list" "M/mailing-list.html")
    ("main loop" "M/main-loop.html")
    ("mainframe" "M/mainframe.html")
    ("mainsleaze" "M/mainsleaze.html")
    ("man page" "M/man-page.html")
    ("management" "M/management.html")
    ("mandelbug" "M/mandelbug.html")
    ("manged" "M/manged.html")
    ("mangle" "M/mangle.html")
    ("mangled name" "M/mangled-name.html")
    ("mangler" "M/mangler.html")
    ("manularity" "M/manularity.html")
    ("marching ants" "M/marching-ants.html")
    ("marbles" "M/marbles.html")
    ("marginal" "M/marginal.html")
    ("marginally" "M/marginally.html")
    ("marketroid" "M/marketroid.html")
    ("Mars" "M/Mars.html")
    ("martian" "M/martian.html")
    ("massage" "M/massage.html")
    ("math-out" "M/math-out.html")
    ("Matrix" "M/Matrix.html")
    ("maximum Maytag mode" "M/maximum-Maytag-mode.html")
    ("McQuary limit" "M/McQuary-limit.html")
    ("meatspace" "M/meatspace.html")
    ("meatware" "M/meatware.html")
    ("meeces" "M/meeces.html")
    ("meg" "M/meg.html")
    ("mega-" "M/mega-.html")
    ("megapenny" "M/megapenny.html")
    ("MEGO" "M/MEGO.html")
    ("meltdown, network" "M/meltdown--network.html")
    ("meme" "M/meme.html")
    ("meme plague" "M/meme-plague.html")
    ("memetics" "M/memetics.html")
    ("memory farts" "M/memory-farts.html")
    ("memory leak" "M/memory-leak.html")
    ("memory smash" "M/memory-smash.html")
    ("menuitis" "M/menuitis.html")
    ("mess-dos" "M/mess-dos.html")
    ("meta" "M/meta.html")
    ("meta bit" "M/meta-bit.html")
    ("metasyntactic variable" "M/metasyntactic-variable.html")
    ("MFTL" "M/MFTL.html")
    ("mickey" "M/mickey.html")
    ("mickey mouse program" "M/mickey-mouse-program.html")
    ("micro-" "M/micro-.html")
    ("MicroDroid" "M/MicroDroid.html")
    ("microfortnight" "M/microfortnight.html")
    ("microLenat" "M/microLenat.html")
    ("microReid" "M/microReid.html")
    ("microserf" "M/microserf.html")
    ("Microsloth Windows" "M/Microsloth-Windows.html")
    ("Microsoft" "M/Microsoft.html")
    ("micros~1" "M/micros-tilde-1.html")
    ("middle-endian" "M/middle-endian.html")
    ("middle-out implementation" "M/middle-out-implementation.html")
    ("milliLampson" "M/milliLampson.html")
    ("minor detail" "M/minor-detail.html")
    ("MIPS" "M/MIPS.html")
    ("misbug" "M/misbug.html")
    ("misfeature" "M/misfeature.html")
    ("missile address" "M/missile-address.html")
    ("MiSTing" "M/MiSTing.html")
    ("miswart" "M/miswart.html")
    ("MMF" "M/MMF.html")
    ("mobo" "M/mobo.html")
    ("moby" "M/moby.html")
    ("mockingbird" "M/mockingbird.html")
    ("mod" "M/mod.html")
    ("mode" "M/mode.html")
    ("mode bit" "M/mode-bit.html")
    ("modulo" "M/modulo.html")
    ("mojibake" "M/mojibake.html")
    ("molly-guard" "M/molly-guard.html")
    ("Mongolian Hordes technique" "M/Mongolian-Hordes-technique.html")
    ("monkey up" "M/monkey-up.html")
    ("monkey, scratch" "M/monkey--scratch.html")
    ("monstrosity" "M/monstrosity.html")
    ("monty" "M/monty.html")
    ("Moof" "M/Moof.html")
    ("Moore's Law" "M/Moores-Law.html")
    ("moria" "M/moria.html")
    ("MOTAS" "M/MOTAS.html")
    ("MOTOS" "M/MOTOS.html")
    ("MOTSS" "M/MOTSS.html")
    ("mouse ahead" "M/mouse-ahead.html")
    ("mouse belt" "M/mouse-belt.html")
    ("mouse droppings" "M/mouse-droppings.html")
    ("mouse elbow" "M/mouse-elbow.html")
    ("mouse pusher" "M/mouse-pusher.html")
    ("mouso" "M/mouso.html")
    ("MS-DOS" "M/MS-DOS.html")
    ("mu" "M/mu.html")
    ("MUD" "M/MUD.html")
    ("muddie" "M/muddie.html")
    ("mudhead" "M/mudhead.html")
    ("muggle" "M/muggle.html")
    ("Multics" "M/Multics.html")
    ("multitask" "M/multitask.html")
    ("mumblage" "M/mumblage.html")
    ("mumble" "M/mumble.html")
    ("munch" "M/munch.html")
    ("munching" "M/munching.html")
    ("munching squares" "M/munching-squares.html")
    ("munchkin" "M/munchkin.html")
    ("mundane" "M/mundane.html")
    ("mung" "M/mung.html")
    ("munge" "M/munge.html")
    ("Murphy's Law" "M/Murphys-Law.html")
    ("music" "M/music.html")
    ("mutter" "M/mutter.html")
    ("N" "N/N.html")
    ("nadger" "N/nadger.html")
    ("nagware" "N/nagware.html")
    ("nailed to the wall" "N/nailed-to-the-wall.html")
    ("nailing jelly" "N/nailing-jelly.html")
    ("naive" "N/naive.html")
    ("naive user" "N/naive-user.html")
    ("NAK" "N/NAK.html")
    ("NANA" "N/NANA.html")
    ("nano" "N/nano.html")
    ("nano-" "N/nano-.html")
    ("nanoacre" "N/nanoacre.html")
    ("nanobot" "N/nanobot.html")
    ("nanocomputer" "N/nanocomputer.html")
    ("nanofortnight" "N/nanofortnight.html")
    ("nanotechnology" "N/nanotechnology.html")
    ("narg" "N/narg.html")
    ("nasal demons" "N/nasal-demons.html")
    ("nastygram" "N/nastygram.html")
    ("Nathan Hale" "N/Nathan-Hale.html")
    ("nature" "N/nature.html")
    ("neat hack" "N/neat-hack.html")
    ("neats vs. scruffies" "N/neats-vs--scruffies.html")
    ("neep-neep" "N/neep-neep.html")
    ("neophilia" "N/neophilia.html")
    ("nerd" "N/nerd.html")
    ("nerd knob" "N/nerd-knob.html")
    ("net.-" "N/net--.html")
    ("net.god" "N/net-god.html")
    ("net.personality" "N/net-personality.html")
    ("net.police" "N/net-police.html")
    ("netburp" "N/netburp.html")
    ("netdead" "N/netdead.html")
    ("nethack" "N/nethack.html")
    ("netiquette" "N/netiquette.html")
    ("netlag" "N/netlag.html")
    ("netnews" "N/netnews.html")
    ("Netscrape" "N/Netscrape.html")
    ("netsplit" "N/netsplit.html")
    ("netter" "N/netter.html")
    ("network address" "N/network-address.html")
    ("network meltdown" "N/network-meltdown.html")
    ("New Jersey" "N/New-Jersey.html")
    ("New Testament" "N/New-Testament.html")
    ("newbie" "N/newbie.html")
    ("newgroup wars" "N/newgroup-wars.html")
    ("newline" "N/newline.html")
    ("NeWS" "N/NeWS.html")
    ("newsfroup" "N/newsfroup.html")
    ("newsgroup" "N/newsgroup.html")
    ("nick" "N/nick.html")
    ("nickle" "N/nickle.html")
    ("night mode" "N/night-mode.html")
    ("Nightmare File System" "N/Nightmare-File-System.html")
    ("NIL" "N/NIL.html")
    ("Ninety-Ninety Rule" "N/Ninety-Ninety-Rule.html")
    ("nipple mouse" "N/nipple-mouse.html")
    ("NMI" "N/NMI.html")
    ("no-op" "N/no-op.html")
    ("noddy" "N/noddy.html")
    ("non-optimal solution" "N/non-optimal-solution.html")
    ("nonlinear" "N/nonlinear.html")
    ("nontrivial" "N/nontrivial.html")
    ("not entirely unlike X" "N/not-entirely-unlike-X.html")
    ("not ready for prime time" "N/not-ready-for-prime-time.html")
    ("notwork" "N/notwork.html")
    ("NP-" "N/NP-.html")
    ("NSA line eater" "N/NSA-line-eater.html")
    ("NSP" "N/NSP.html")
    ("nude" "N/nude.html")
    ("nugry" "N/nugry.html")
    ("nuke" "N/nuke.html")
    ("number-crunching" "N/number-crunching.html")
    ("numbers" "N/numbers.html")
    ("NUXI problem" "N/NUXI-problem.html")
    ("nybble" "N/nybble.html")
    ("nyetwork" "N/nyetwork.html")
    ("Ob-" "O/Ob-.html")
    ("Obfuscated C Contest" "O/Obfuscated-C-Contest.html")
    ("obi-wan error" "O/obi-wan-error.html")
    ("Objectionable-C" "O/Objectionable-C.html")
    ("obscure" "O/obscure.html")
    ("octal forty" "O/octal-forty.html")
    ("off the trolley" "O/off-the-trolley.html")
    ("off-by-one error" "O/off-by-one-error.html")
    ("offline" "O/offline.html")
    ("ogg" "O/ogg.html")
    ("-oid" "O/suffix-oid.html")
    ("old fart" "O/old-fart.html")
    ("Old Testament" "O/Old-Testament.html")
    ("on the gripping hand" "O/on-the-gripping-hand.html")
    ("one-banana problem" "O/one-banana-problem.html")
    ("one-line fix" "O/one-line-fix.html")
    ("one-liner wars" "O/one-liner-wars.html")
    ("ooblick" "O/ooblick.html")
    ("OP" "O/thread-OP.html")
    ("op" "O/op.html")
    ("open" "O/open.html")
    ("open source" "O/open-source.html")
    ("open switch" "O/open-switch.html")
    ("operating system" "O/operating-system.html")
    ("operator headspace" "O/operator-headspace.html")
    ("optical diff" "O/optical-diff.html")
    ("optical grep" "O/optical-grep.html")
    ("optimism" "O/optimism.html")
    ("Oracle, the" "O/Oracle--the.html")
    ("Orange Book" "O/Orange-Book.html")
    ("oriental food" "O/oriental-food.html")
    ("orphan" "O/orphan.html")
    ("orphaned i-node" "O/orphaned-i-node.html")
    ("orthogonal" "O/orthogonal.html")
    ("OS" "O/OS.html")
    ("OS/2" "O/OS-2.html")
    ("OSS" "O/OSS.html")
    ("OT" "O/OT.html")
    ("OTOH" "O/OTOH.html")
    ("out-of-band" "O/out-of-band.html")
    ("overclock" "O/overclock.html")
    ("overflow bit" "O/overflow-bit.html")
    ("overrun" "O/overrun.html")
    ("overrun screw" "O/overrun-screw.html")
    ("owned" "O/owned.html")
    ("P.O.D." "P/P-O-D-.html")
    ("packet over air" "P/packet-over-air.html")
    ("padded cell" "P/padded-cell.html")
    ("page in" "P/page-in.html")
    ("page out" "P/page-out.html")
    ("pain in the net" "P/pain-in-the-net.html")
    ("paper-net" "P/paper-net.html")
    ("param" "P/param.html")
    ("PARC" "P/PARC.html")
    ("parent message" "P/parent-message.html")
    ("parity errors" "P/parity-errors.html")
    ("Parkinson's Law of Data" "P/Parkinsons-Law-of-Data.html")
    ("parm" "P/parm.html")
    ("parse" "P/parse.html")
    ("Pascal" "P/Pascal.html")
    ("PascalCasing" "P/PascalCasing.html")
    ("pastie" "P/pastie.html")
    ("patch" "P/patch.html")
    ("patch pumpkin" "P/patch-pumpkin.html")
    ("patch space" "P/patch-space.html")
    ("path" "P/path.html")
    ("pathological" "P/pathological.html")
    ("payware" "P/payware.html")
    ("PBD" "P/PBD.html")
    ("PD" "P/PD.html")
    ("PDP-10" "P/PDP-10.html")
    ("PDP-11" "P/PDP-11.html")
    ("PDP-20" "P/PDP-20.html")
    ("PEBKAC" "P/PEBKAC.html")
    ("peek" "P/peek.html")
    ("pencil and paper" "P/pencil-and-paper.html")
    ("Pentagram Pro" "P/Pentagram-Pro.html")
    ("Pentium" "P/Pentium.html")
    ("peon" "P/peon.html")
    ("percent-S" "P/percent-S.html")
    ("perf" "P/perf.html")
    ("perfect programmer syndrome" "P/perfect-programmer-syndrome.html")
    ("Perl" "P/Perl.html")
    ("person of no account" "P/person-of-no-account.html")
    ("pessimal" "P/pessimal.html")
    ("pessimizing compiler" "P/pessimizing-compiler.html")
    ("peta-" "P/peta-.html")
    ("pffft" "P/pffft.html")
    ("PFY" "P/PFY.html")
    ("phage" "P/phage.html")
    ("phase" "P/phase.html")
    ("phase of the moon" "P/phase-of-the-moon.html")
    ("phase-wrapping" "P/phase-wrapping.html")
    ("PHB" "P/PHB.html")
    ("phreaker" "P/phreaker.html")
    ("phreaking" "P/phreaking.html")
    ("pico-" "P/pico-.html")
    ("pig-tail" "P/pig-tail.html")
    ("pilot error" "P/pilot-error.html")
    ("ping" "P/ping.html")
    ("Ping O' Death" "P/Ping-O--Death.html")
    ("ping storm" "P/ping-storm.html")
    ("pink contract" "P/pink-contract.html")
    ("pink wire" "P/pink-wire.html")
    ("pipe" "P/pipe.html")
    ("pistol" "P/pistol.html")
    ("pixel sort" "P/pixel-sort.html")
    ("pizza box" "P/pizza-box.html")
    ("plaid screen" "P/plaid-screen.html")
    ("plain-ASCII" "P/plain-ASCII.html")
    ("Plan 9" "P/Plan-9.html")
    ("plan file" "P/plan-file.html")
    ("platinum-iridium" "P/platinum-iridium.html")
    ("playpen" "P/playpen.html")
    ("playte" "P/playte.html")
    ("plokta" "P/plokta.html")
    ("plonk" "P/plonk.html")
    ("plug-and-pray" "P/plug-and-pray.html")
    ("plugh" "P/plugh.html")
    ("plumbing" "P/plumbing.html")
    ("PM" "P/PM.html")
    ("point-and-drool interface" "P/point-and-drool-interface.html")
    ("pointy hat" "P/pointy-hat.html")
    ("pointy-haired" "P/pointy-haired.html")
    ("poke" "P/poke.html")
    ("poll" "P/poll.html")
    ("polygon pusher" "P/polygon-pusher.html")
    ("POM" "P/POM.html")
    ("ponytail" "P/ponytail.html")
    ("pop" "P/pop.html")
    ("poser" "P/poser.html")
    ("post" "P/post.html")
    ("postcardware" "P/postcardware.html")
    ("Postel's Prescription" "P/Postels-Prescription.html")
    ("posting" "P/posting.html")
    ("postmaster" "P/postmaster.html")
    ("PostScript" "P/PostScript.html")
    ("pound on" "P/pound-on.html")
    ("power cycle" "P/power-cycle.html")
    ("power hit" "P/power-hit.html")
    ("pr0n" "P/pr0n.html")
    ("precedence lossage" "P/precedence-lossage.html")
    ("pred" "P/pred.html")
    ("prepend" "P/prepend.html")
    ("prestidigitization" "P/prestidigitization.html")
    ("pretty pictures" "P/pretty-pictures.html")
    ("prettyprint" "P/prettyprint.html")
    ("pretzel key" "P/pretzel-key.html")
    ("priesthood" "P/priesthood.html")
    ("prime time" "P/prime-time.html")
    ("print" "P/print.html")
    ("printing discussion" "P/printing-discussion.html")
    ("priority interrupt" "P/priority-interrupt.html")
    ("profile" "P/profile.html")
    ("progasm" "P/progasm.html")
    ("proggy" "P/proggy.html")
    ("proglet" "P/proglet.html")
    ("program" "P/program.html")
    ("Programmer's Cheer" "P/Programmers-Cheer.html")
    ("programming" "P/programming.html")
    ("programming fluid" "P/programming-fluid.html")
    ("propeller head" "P/propeller-head.html")
    ("propeller key" "P/propeller-key.html")
    ("proprietary" "P/proprietary.html")
    ("protocol" "P/protocol.html")
    ("provocative maintenance" "P/provocative-maintenance.html")
    ("prowler" "P/prowler.html")
    ("pseudo" "P/pseudo.html")
    ("pseudoprime" "P/pseudoprime.html")
    ("pseudosuit" "P/pseudosuit.html")
    ("psychedelicware" "P/psychedelicware.html")
    ("psyton" "P/psyton.html")
    ("pubic directory" "P/pubic-directory.html")
    ("puff" "P/puff.html")
    ("pumpkin holder" "P/pumpkin-holder.html")
    ("pumpking" "P/pumpking.html")
    ("punched card" "P/punched-card.html")
    ("punt" "P/punt.html")
    ("Purple Book" "P/Purple-Book.html")
    ("purple wire" "P/purple-wire.html")
    ("push" "P/push.html")
    ("Python" "P/Python.html")
    ("quad" "Q/quad.html")
    ("quadruple bucky" "Q/quadruple-bucky.html")
    ("quantifiers" "Q/quantifiers.html")
    ("quantum bogodynamics" "Q/quantum-bogodynamics.html")
    ("quarter" "Q/quarter.html")
    ("ques" "Q/ques.html")
    ("quick-and-dirty" "Q/quick-and-dirty.html")
    ("quine" "Q/quine.html")
    ("Quirk objection" "Q/Quirk-objection.html")
    ("quote chapter and verse" "Q/quote-chapter-and-verse.html")
    ("quotient" "Q/quotient.html")
    ("quux" "Q/quux.html")
    ("qux" "Q/qux.html")
    ("QWERTY" "Q/QWERTY.html")
    ("rabbit job" "R/rabbit-job.html")
    ("rain dance" "R/rain-dance.html")
    ("rainbow series" "R/rainbow-series.html")
    ("random" "R/random.html")
    ("Random Number God" "R/Random-Number-God.html")
    ("random numbers" "R/random-numbers.html")
    ("randomness" "R/randomness.html")
    ("rape" "R/rape.html")
    ("rare mode" "R/rare-mode.html")
    ("raster blaster" "R/raster-blaster.html")
    ("raster burn" "R/raster-burn.html")
    ("rasterbation" "R/rasterbation.html")
    ("rat belt" "R/rat-belt.html")
    ("rat dance" "R/rat-dance.html")
    ("rathole" "R/rathole.html")
    ("ratio site" "R/ratio-site.html")
    ("rave" "R/rave.html")
    ("rave on!" "R/rave-on-.html")
    ("ravs" "R/ravs.html")
    ("raw mode" "R/raw-mode.html")
    ("RBL" "R/RBL.html")
    ("rc file" "R/rc-file.html")
    ("RE" "R/RE.html")
    ("read-only user" "R/read-only-user.html")
    ("README file" "R/README-file.html")
    ("real" "R/real.html")
    ("real estate" "R/real-estate.html")
    ("real hack" "R/real-hack.html")
    ("real operating system" "R/real-operating-system.html")
    ("Real Programmer" "R/Real-Programmer.html")
    ("Real Soon Now" "R/Real-Soon-Now.html")
    ("real time" "R/real-time.html")
    ("real user" "R/real-user.html")
    ("Real World" "R/Real-World.html")
    ("reality check" "R/reality-check.html")
    ("reality-distortion field" "R/reality-distortion-field.html")
    ("reaper" "R/reaper.html")
    ("recompile the world" "R/recompile-the-world.html")
    ("rectangle slinger" "R/rectangle-slinger.html")
    ("recursion" "R/recursion.html")
    ("recursive acronym" "R/recursive-acronym.html")
    ("red wire" "R/red-wire.html")
    ("regexp" "R/regexp.html")
    ("register dancing" "R/register-dancing.html")
    ("rehi" "R/rehi.html")
    ("reincarnation, cycle of" "R/reincarnation--cycle-of.html")
    ("reinvent the wheel" "R/reinvent-the-wheel.html")
    ("relay rape" "R/relay-rape.html")
    ("religion of CHI" "R/religion-of-CHI.html")
    ("religious issues" "R/religious-issues.html")
    ("replicator" "R/replicator.html")
    ("reply" "R/reply.html")
    ("restriction" "R/restriction.html")
    ("retcon" "R/retcon.html")
    ("RETI" "R/RETI.html")
    ("retrocomputing" "R/retrocomputing.html")
    ("return from the dead" "R/return-from-the-dead.html")
    ("RFC" "R/RFC.html")
    ("RFE" "R/RFE.html")
    ("Right Thing" "R/Right-Thing.html")
    ("rip" "R/rip.html")
    ("ripoff" "R/ripoff.html")
    ("RL" "R/RL.html")
    ("roach" "R/roach.html")
    ("robocanceller" "R/robocanceller.html")
    ("robot" "R/robot.html")
    ("robust" "R/robust.html")
    ("rococo" "R/rococo.html")
    ("rogue" "R/rogue.html")
    ("room-temperature IQ" "R/room-temperature-IQ.html")
    ("root" "R/root.html")
    ("root mode" "R/root-mode.html")
    ("rootkit" "R/rootkit.html")
    ("rot13" "R/rot13.html")
    ("rotary debugger" "R/rotary-debugger.html")
    ("RSN" "R/RSN.html")
    ("RTBM" "R/RTBM.html")
    ("RTFAQ" "R/RTFAQ.html")
    ("RTFB" "R/RTFB.html")
    ("RTFM" "R/RTFM.html")
    ("RTFS" "R/RTFS.html")
    ("RTI" "R/RTI.html")
    ("RTM" "R/RTM.html")
    ("RTS" "R/RTS.html")
    ("rubber-hose cryptanalysis" "R/rubber-hose-cryptanalysis.html")
    ("rude" "R/rude.html")
    ("runes" "R/runes.html")
    ("runic" "R/runic.html")
    ("rusty iron" "R/rusty-iron.html")
    ("rusty wire" "R/rusty-wire.html")
    ("S/N ratio" "S/S-N-ratio.html")
    ("sacred" "S/sacred.html")
    ("saga" "S/saga.html")
    ("sagan" "S/sagan.html")
    ("SAIL" "S/SAIL.html")
    ("salescritter" "S/salescritter.html")
    ("salt" "S/salt.html")
    ("salt mines" "S/salt-mines.html")
    ("salt substrate" "S/salt-substrate.html")
    ("same-day service" "S/same-day-service.html")
    ("samizdat" "S/samizdat.html")
    ("samurai" "S/samurai.html")
    ("sandbender" "S/sandbender.html")
    ("sandbox" "S/sandbox.html")
    ("sanity check" "S/sanity-check.html")
    ("Saturday-night special" "S/Saturday-night-special.html")
    ("say" "S/say.html")
    ("scag" "S/scag.html")
    ("scanno" "S/scanno.html")
    ("scary devil monastery" "S/scary-devil-monastery.html")
    ("schroedinbug" "S/schroedinbug.html")
    ("science-fiction fandom" "S/science-fiction-fandom.html")
    ("SCNR" "S/SCNR.html")
    ("scram switch" "S/scram-switch.html")
    ("scratch" "S/scratch.html")
    ("scratch monkey" "S/scratch-monkey.html")
    ("scream and die" "S/scream-and-die.html")
    ("screaming tty" "S/screaming-tty.html")
    ("screen" "S/screen.html")
    ("screen name" "S/screen-name.html")
    ("screen scraping" "S/screen-scraping.html")
    ("screw" "S/screw.html")
    ("screwage" "S/screwage.html")
    ("scribble" "S/scribble.html")
    ("script kiddies" "S/script-kiddies.html")
    ("scrog" "S/scrog.html")
    ("scrool" "S/scrool.html")
    ("scrozzle" "S/scrozzle.html")
    ("scruffies" "S/scruffies.html")
    ("SCSI" "S/SCSI.html")
    ("SCSI voodoo" "S/SCSI-voodoo.html")
    ("search-and-destroy mode" "S/search-and-destroy-mode.html")
    ("second-system effect" "S/second-system-effect.html")
    ("secondary damage" "S/secondary-damage.html")
    ("security through obscurity" "S/security-through-obscurity.html")
    ("SED" "S/SED.html")
    ("See figure 1" "S/See-figure-1.html")
    ("segfault" "S/segfault.html")
    ("seggie" "S/seggie.html")
    ("segment" "S/segment.html")
    ("segmentation fault" "S/segmentation-fault.html")
    ("segv" "S/segv.html")
    ("self-reference" "S/self-reference.html")
    ("selvage" "S/selvage.html")
    ("semi" "S/semi.html")
    ("semi-automated" "S/semi-automated.html")
    ("semi-infinite" "S/semi-infinite.html")
    ("senior bit" "S/senior-bit.html")
    ("September that never ended" "S/September-that-never-ended.html")
    ("server" "S/server.html")
    ("SEX" "S/SEX.html")
    ("sex changer" "S/sex-changer.html")
    ("shambolic link" "S/shambolic-link.html")
    ("shar file" "S/shar-file.html")
    ("sharchive" "S/sharchive.html")
    ("Share and enjoy!" "S/Share-and-enjoy-.html")
    ("shareware" "S/shareware.html")
    ("sharing violation" "S/sharing-violation.html")
    ("shebang" "S/shebang.html")
    ("shelfware" "S/shelfware.html")
    ("shell" "S/shell.html")
    ("shell out" "S/shell-out.html")
    ("shift left (or right) logical" "S/shift-left-or-right-logical.html")
    ("shim" "S/shim.html")
    ("shitogram" "S/shitogram.html")
    ("shotgun debugging" "S/shotgun-debugging.html")
    ("shovelware" "S/shovelware.html")
    ("showstopper" "S/showstopper.html")
    ("shriek" "S/shriek.html")
    ("Shub-Internet" "S/Shub-Internet.html")
    ("SIG" "S/SIG.html")
    ("sig block" "S/sig-block.html")
    ("sig quote" "S/sig-quote.html")
    ("sig virus" "S/sig-virus.html")
    ("sigmonster" "S/sigmonster.html")
    ("signal-to-noise ratio" "S/signal-to-noise-ratio.html")
    ("silicon" "S/silicon.html")
    ("silly walk" "S/silly-walk.html")
    ("silo" "S/silo.html")
    ("since time T equals minus infinity" "S/since-time-T-equals-minus-infinity.html")
    ("sitename" "S/sitename.html")
    ("skrog" "S/skrog.html")
    ("skulker" "S/skulker.html")
    ("slab" "S/slab.html")
    ("slack" "S/slack.html")
    ("slash" "S/slash.html")
    ("slashdot effect" "S/slashdot-effect.html")
    ("sleep" "S/sleep.html")
    ("slim" "S/slim.html")
    ("slop" "S/slop.html")
    ("slopsucker" "S/slopsucker.html")
    ("Slowlaris" "S/Slowlaris.html")
    ("slurp" "S/slurp.html")
    ("slurp the robot" "S/slurp-the-robot.html")
    ("smart" "S/smart.html")
    ("smart terminal" "S/smart-terminal.html")
    ("smash case" "S/smash-case.html")
    ("smash the stack" "S/smash-the-stack.html")
    ("smiley" "S/smiley.html")
    ("smoke" "S/smoke.html")
    ("smoke and mirrors" "S/smoke-and-mirrors.html")
    ("smoke test" "S/smoke-test.html")
    ("smoking clover" "S/smoking-clover.html")
    ("smoot" "S/smoot.html")
    ("SMOP" "S/SMOP.html")
    ("smurf" "S/smurf.html")
    ("SNAFU principle" "S/SNAFU-principle.html")
    ("snail" "S/snail.html")
    ("snail-mail" "S/snail-mail.html")
    ("snap" "S/snap.html")
    ("snarf" "S/snarf.html")
    ("snarf &amp; barf" "S/snarf-ampersand-barf.html")
    ("snarf down" "S/snarf-down.html")
    ("snark" "S/snark.html")
    ("sneaker" "S/sneaker.html")
    ("sneakernet" "S/sneakernet.html")
    ("sniff" "S/sniff.html")
    ("SO" "S/SO.html")
    ("social engineering" "S/social-engineering.html")
    ("social science number" "S/social-science-number.html")
    ("sock puppet" "S/sock-puppet.html")
    ("sodium substrate" "S/sodium-substrate.html")
    ("soft boot" "S/soft-boot.html")
    ("softcopy" "S/softcopy.html")
    ("software bloat" "S/software-bloat.html")
    ("software hoarding" "S/software-hoarding.html")
    ("software laser" "S/software-laser.html")
    ("software rot" "S/software-rot.html")
    ("softwarily" "S/softwarily.html")
    ("softy" "S/softy.html")
    ("some random X" "S/some-random-X.html")
    ("sorcerer's apprentice mode" "S/sorcerers-apprentice-mode.html")
    ("source" "S/source.html")
    ("source of all good bits" "S/source-of-all-good-bits.html")
    ("space-cadet keyboard" "S/space-cadet-keyboard.html")
    ("spaceship operator" "S/spaceship-operator.html")
    ("SPACEWAR" "S/SPACEWAR.html")
    ("spaghetti code" "S/spaghetti-code.html")
    ("spaghetti inheritance" "S/spaghetti-inheritance.html")
    ("spam" "S/spam.html")
    ("spam bait" "S/spam-bait.html")
    ("spamblock" "S/spamblock.html")
    ("spamhaus" "S/spamhaus.html")
    ("spamvertize" "S/spamvertize.html")
    ("spangle" "S/spangle.html")
    ("spawn" "S/spawn.html")
    ("special-case" "S/special-case.html")
    ("speed of light" "S/speed-of-light.html")
    ("speedometer" "S/speedometer.html")
    ("spell" "S/spell.html")
    ("spelling flame" "S/spelling-flame.html")
    ("spider" "S/spider.html")
    ("spider food" "S/spider-food.html")
    ("spiffy" "S/spiffy.html")
    ("spike" "S/spike.html")
    ("spin" "S/spin.html")
    ("Spinning Pizza of Death" "S/Spinning-Pizza-of-Death.html")
    ("spl" "S/spl.html")
    ("splash screen" "S/splash-screen.html")
    ("splat" "S/splat.html")
    ("splat out" "S/splat-out.html")
    ("splork!" "S/splork-.html")
    ("spod" "S/spod.html")
    ("spoiler" "S/spoiler.html")
    ("spoiler space" "S/spoiler-space.html")
    ("sponge" "S/sponge.html")
    ("spoof" "S/spoof.html")
    ("spool" "S/spool.html")
    ("spool file" "S/spool-file.html")
    ("sporgery" "S/sporgery.html")
    ("sport death" "S/sport-death.html")
    ("spungle" "S/spungle.html")
    ("spyware" "S/spyware.html")
    ("squirrelcide" "S/squirrelcide.html")
    ("stack" "S/stack.html")
    ("stack puke" "S/stack-puke.html")
    ("stale pointer bug" "S/stale-pointer-bug.html")
    ("Stanford Bunny" "S/Stanford-Bunny.html")
    ("star out" "S/star-out.html")
    ("state" "S/state.html")
    ("stealth manager" "S/stealth-manager.html")
    ("steam-powered" "S/steam-powered.html")
    ("steved" "S/steved.html")
    ("STFW" "S/STFW.html")
    ("stir-fried random" "S/stir-fried-random.html")
    ("stomp on" "S/stomp-on.html")
    ("Stone Age" "S/Stone-Age.html")
    ("stone knives and bearskins" "S/stone-knives-and-bearskins.html")
    ("stoppage" "S/stoppage.html")
    ("store" "S/store.html")
    ("STR" "S/STR.html")
    ("strided" "S/strided.html")
    ("stroke" "S/stroke.html")
    ("strudel" "S/strudel.html")
    ("stubroutine" "S/stubroutine.html")
    ("studly" "S/studly.html")
    ("studlycaps" "S/studlycaps.html")
    ("stunning" "S/stunning.html")
    ("stupid-sort" "S/stupid-sort.html")
    ("Stupids" "S/Stupids.html")
    ("Sturgeon's Law" "S/Sturgeons-Law.html")
    ("sucking mud" "S/sucking-mud.html")
    ("sufficiently small" "S/sufficiently-small.html")
    ("suit" "S/suit.html")
    ("suitable win" "S/suitable-win.html")
    ("suitably small" "S/suitably-small.html")
    ("Sun" "S/Sun.html")
    ("sun lounge" "S/sun-lounge.html")
    ("sun-stools" "S/sun-stools.html")
    ("sunspots" "S/sunspots.html")
    ("super source quench" "S/super-source-quench.html")
    ("superloser" "S/superloser.html")
    ("superprogrammer" "S/superprogrammer.html")
    ("superuser" "S/superuser.html")
    ("support" "S/support.html")
    ("surf" "S/surf.html")
    ("Suzie COBOL" "S/Suzie-COBOL.html")
    ("swab" "S/swab.html")
    ("swap" "S/swap.html")
    ("swap space" "S/swap-space.html")
    ("swapped in" "S/swapped-in.html")
    ("swapped out" "S/swapped-out.html")
    ("Swiss-Army chainsaw" "S/Swiss-Army-chainsaw.html")
    ("swizzle" "S/swizzle.html")
    ("sync" "S/sync.html")
    ("syntactic salt" "S/syntactic-salt.html")
    ("syntactic sugar" "S/syntactic-sugar.html")
    ("sys-frog" "S/sys-frog.html")
    ("sysadmin" "S/sysadmin.html")
    ("sysape" "S/sysape.html")
    ("sysop" "S/sysop.html")
    ("system" "S/system.html")
    ("system mangler" "S/system-mangler.html")
    ("systems jock" "S/systems-jock.html")
    ("T" "T/T.html")
    ("tail recursion" "T/tail-recursion.html")
    ("talk mode" "T/talk-mode.html")
    ("talker system" "T/talker-system.html")
    ("TAN" "T/TAN.html")
    ("tanked" "T/tanked.html")
    ("TANSTAAFL" "T/TANSTAAFL.html")
    ("tape monkey" "T/tape-monkey.html")
    ("tar and feather" "T/tar-and-feather.html")
    ("tarball" "T/tarball.html")
    ("tardegy" "T/tardegy.html")
    ("taste" "T/taste.html")
    ("tayste" "T/tayste.html")
    ("TCB" "T/TCB.html")
    ("TCP/IP" "T/TCP-IP.html")
    ("TECO" "T/TECO.html")
    ("tee" "T/tee.html")
    ("teergrube" "T/teergrube.html")
    ("teledildonics" "T/teledildonics.html")
    ("ten-finger interface" "T/ten-finger-interface.html")
    ("tense" "T/tense.html")
    ("tentacle" "T/tentacle.html")
    ("tenured graduate student" "T/tenured-graduate-student.html")
    ("tera-" "T/tera-.html")
    ("teraflop club" "T/teraflop-club.html")
    ("terminak" "T/terminak.html")
    ("terminal brain death" "T/terminal-brain-death.html")
    ("terminal illness" "T/terminal-illness.html")
    ("terminal junkie" "T/terminal-junkie.html")
    ("test" "T/test.html")
    ("TeX" "T/TeX.html")
    ("text" "T/text.html")
    ("thanks in advance" "T/thanks-in-advance.html")
    ("That's not a bug, that's a feature!" "T/Thats-not-a-bug--thats-a-feature-.html")
    ("the literature" "T/the-literature.html")
    ("the network" "T/the-network.html")
    ("the X that can be Y is not the true X" "T/the-X-that-can-be-Y-is-not-the-true-X.html")
    ("theology" "T/theology.html")
    ("theory" "T/theory.html")
    ("thinko" "T/thinko.html")
    ("This can't happen" "T/This-can-t-happen.html")
    ("This time, for sure!" "T/This-time--for-sure-.html")
    ("thrash" "T/thrash.html")
    ("thread" "T/thread.html")
    ("three-finger salute" "T/three-finger-salute.html")
    ("throwaway account" "T/throwaway-account.html")
    ("thud" "T/thud.html")
    ("thumb" "T/thumb.html")
    ("thundering herd problem" "T/thundering-herd-problem.html")
    ("thunk" "T/thunk.html")
    ("tick" "T/tick.html")
    ("tick-list features" "T/tick-list-features.html")
    ("tickle a bug" "T/tickle-a-bug.html")
    ("tiger team" "T/tiger-team.html")
    ("time bomb" "T/time-bomb.html")
    ("time sink" "T/time-sink.html")
    ("time T" "T/time-T.html")
    ("times-or-divided-by" "T/times-or-divided-by.html")
    ("timesharing" "T/timesharing.html")
    ("TINC" "T/TINC.html")
    ("Tinkerbell program" "T/Tinkerbell-program.html")
    ("TINLC" "T/TINLC.html")
    ("tip of the ice-cube" "T/tip-of-the-ice-cube.html")
    ("tired iron" "T/tired-iron.html")
    ("tits on a keyboard" "T/tits-on-a-keyboard.html")
    ("TLA" "T/TLA.html")
    ("TMRC" "T/TMRC.html")
    ("TMRCie" "T/TMRCie.html")
    ("TMTOWTDI" "T/TMTOWTDI.html")
    ("to a first approximation" "T/to-a-first-approximation.html")
    ("to a zeroth approximation" "T/to-a-zeroth-approximation.html")
    ("toad" "T/toad.html")
    ("toast" "T/toast.html")
    ("toaster" "T/toaster.html")
    ("toeprint" "T/toeprint.html")
    ("TOFU" "T/TOFU.html")
    ("toggle" "T/toggle.html")
    ("tool" "T/tool.html")
    ("toolchain" "T/toolchain.html")
    ("toolsmith" "T/toolsmith.html")
    ("toor" "T/toor.html")
    ("top-post" "T/top-post.html")
    ("topic drift" "T/topic-drift.html")
    ("topic group" "T/topic-group.html")
    ("TOPS-10" "T/TOPS-10.html")
    ("TOPS-20" "T/TOPS-20.html")
    ("TOS" "T/TOS.html")
    ("tourist" "T/tourist.html")
    ("tourist information" "T/tourist-information.html")
    ("touristic" "T/touristic.html")
    ("toy" "T/toy.html")
    ("toy language" "T/toy-language.html")
    ("toy problem" "T/toy-problem.html")
    ("toy program" "T/toy-program.html")
    ("trampoline" "T/trampoline.html")
    ("trap" "T/trap.html")
    ("trap door" "T/trap-door.html")
    ("trash" "T/trash.html")
    ("trawl" "T/trawl.html")
    ("tree-killer" "T/tree-killer.html")
    ("treeware" "T/treeware.html")
    ("trit" "T/trit.html")
    ("trivial" "T/trivial.html")
    ("troff" "T/troff.html")
    ("troglodyte" "T/troglodyte.html")
    ("troglodyte mode" "T/troglodyte-mode.html")
    ("Trojan horse" "T/Trojan-horse.html")
    ("troll" "T/troll.html")
    ("Troll-O-Meter" "T/Troll-O-Meter.html")
    ("tron" "T/tron.html")
    ("troughie" "T/troughie.html")
    ("true-hacker" "T/true-hacker.html")
    ("tty" "T/tty.html")
    ("tube" "T/tube.html")
    ("tube time" "T/tube-time.html")
    ("tunafish" "T/tunafish.html")
    ("tune" "T/tune.html")
    ("turbo nerd" "T/turbo-nerd.html")
    ("Turing tar-pit" "T/Turing-tar-pit.html")
    ("turist" "T/turist.html")
    ("Tux" "T/Tux.html")
    ("tweak" "T/tweak.html")
    ("TWENEX" "T/TWENEX.html")
    ("twiddle" "T/twiddle.html")
    ("twilight zone" "T/twilight-zone.html")
    ("twink" "T/twink.html")
    ("twirling baton" "T/twirling-baton.html")
    ("two pi" "T/two-pi.html")
    ("two-to-the-N" "T/two-to-the-N.html")
    ("u-" "U/u-.html")
    ("UBD" "U/UBD.html")
    ("UBE" "U/UBE.html")
    ("ubergeek" "U/ubergeek.html")
    ("UCE" "U/UCE.html")
    ("UDP" "U/UDP.html")
    ("UN*X" "U/UN-asterisk-X.html")
    ("undefined external reference" "U/undefined-external-reference.html")
    ("under the hood" "U/under-the-hood.html")
    ("undocumented feature" "U/undocumented-feature.html")
    ("uninteresting" "U/uninteresting.html")
    ("Unix" "U/Unix.html")
    ("Unix brain damage" "U/Unix-brain-damage.html")
    ("Unix conspiracy" "U/Unix-conspiracy.html")
    ("Unix weenie" "U/Unix-weenie.html")
    ("unixism" "U/unixism.html")
    ("unswizzle" "U/unswizzle.html")
    ("unwind the stack" "U/unwind-the-stack.html")
    ("unwind-protect" "U/unwind-protect.html")
    ("up" "U/up.html")
    ("upload" "U/upload.html")
    ("upstream" "U/upstream.html")
    ("upthread" "U/upthread.html")
    ("uptime" "U/uptime.html")
    ("urchin" "U/urchin.html")
    ("URL" "U/URL.html")
    ("Usenet" "U/Usenet.html")
    ("Usenet Death Penalty" "U/Usenet-Death-Penalty.html")
    ("user" "U/user.html")
    ("user-friendly" "U/user-friendly.html")
    ("user-obsequious" "U/user-obsequious.html")
    ("userland" "U/userland.html")
    ("Utah teapot, the" "U/Utah-teapot.html")
    ("UTSL" "U/UTSL.html")
    ("UUOC" "U/UUOC.html")
    ("V7" "V/V7.html")
    ("vadding" "V/vadding.html")
    ("vanilla" "V/vanilla.html")
    ("vanity domain" "V/vanity-domain.html")
    ("vannevar" "V/vannevar.html")
    ("vaporware" "V/vaporware.html")
    ("var" "V/var.html")
    ("vaston" "V/vaston.html")
    ("VAX" "V/VAX.html")
    ("VAXen" "V/VAXen.html")
    ("vaxocentrism" "V/vaxocentrism.html")
    ("vdiff" "V/vdiff.html")
    ("veeblefester" "V/veeblefester.html")
    ("velveeta" "V/velveeta.html")
    ("Venus flytrap" "V/Venus-flytrap.html")
    ("verbage" "V/verbage.html")
    ("verbiage" "V/verbiage.html")
    ("Version 7" "V/Version-7.html")
    ("vgrep" "V/vgrep.html")
    ("vi" "V/vi.html")
    ("video toaster" "V/video-toaster.html")
    ("videotex" "V/videotex.html")
    ("virgin" "V/virgin.html")
    ("virtual" "V/virtual.html")
    ("virtual beer" "V/virtual-beer.html")
    ("virtual Friday" "V/virtual-Friday.html")
    ("virtual reality" "V/virtual-reality.html")
    ("virtual shredder" "V/virtual-shredder.html")
    ("virus" "V/virus.html")
    ("visionary" "V/visionary.html")
    ("VMS" "V/VMS.html")
    ("voice" "V/voice.html")
    ("voice-net" "V/voice-net.html")
    ("voodoo programming" "V/voodoo-programming.html")
    ("VR" "V/VR.html")
    ("Vulcan nerve pinch" "V/Vulcan-nerve-pinch.html")
    ("vulture capitalist" "V/vulture-capitalist.html")
    ("w00t" "W/w00t.html")
    ("wabbit" "W/wabbit.html")
    ("WAITS" "W/WAITS.html")
    ("waldo" "W/waldo.html")
    ("walk" "W/walk.html")
    ("walk off the end of" "W/walk-off-the-end-of.html")
    ("walking drives" "W/walking-drives.html")
    ("wall" "W/wall.html")
    ("wall follower" "W/wall-follower.html")
    ("wall time" "W/wall-time.html")
    ("wall wart" "W/wall-wart.html")
    ("wallhack" "W/wallhack.html")
    ("wango" "W/wango.html")
    ("wank" "W/wank.html")
    ("wannabee" "W/wannabee.html")
    ("war dialer" "W/war-dialer.html")
    ("war-driving" "W/war-driving.html")
    ("war-chalking" "W/war-chalking.html")
    ("-ware" "W/suffix-ware.html")
    ("warez" "W/warez.html")
    ("warez d00dz" "W/warez-d00dz.html")
    ("warez kiddies" "W/warez-kiddies.html")
    ("warlording" "W/warlording.html")
    ("warm boot" "W/warm-boot.html")
    ("wart" "W/wart.html")
    ("washing machine" "W/washing-machine.html")
    ("washing software" "W/washing-software.html")
    ("water MIPS" "W/water-MIPS.html")
    ("wave a dead chicken" "W/wave-a-dead-chicken.html")
    ("weasel" "W/weasel.html")
    ("web pointer" "W/web-pointer.html")
    ("web ring" "W/web-ring.html")
    ("web toaster" "W/web-toaster.html")
    ("webify" "W/webify.html")
    ("webmaster" "W/webmaster.html")
    ("wedged" "W/wedged.html")
    ("wedgie" "W/wedgie.html")
    ("wedgitude" "W/wedgitude.html")
    ("weeble" "W/weeble.html")
    ("weeds" "W/weeds.html")
    ("weenie" "W/weenie.html")
    ("Weenix" "W/Weenix.html")
    ("well-behaved" "W/well-behaved.html")
    ("well-connected" "W/well-connected.html")
    ("wetware" "W/wetware.html")
    ("whack" "W/whack.html")
    ("whack-a-mole" "W/whack-a-mole.html")
    ("whacker" "W/whacker.html")
    ("whales" "W/whales.html")
    ("What's a spline?" "W/Whats-a-spline.html")
    ("wheel" "W/wheel.html")
    ("wheel bit" "W/wheel-bit.html")
    ("wheel of reincarnation" "W/wheel-of-reincarnation.html")
    ("wheel wars" "W/wheel-wars.html")
    ("white hat" "W/white-hat.html")
    ("whitelist" "W/whitelist.html")
    ("whizzy" "W/whizzy.html")
    ("Whorfian mind-lock" "W/Whorfian-mind-lock.html")
    ("wibble" "W/wibble.html")
    ("WIBNI" "W/WIBNI.html")
    ("widget" "W/widget.html")
    ("wiggles" "W/wiggles.html")
    ("wild side" "W/wild-side.html")
    ("WIMP environment" "W/WIMP-environment.html")
    ("win" "W/win.html")
    ("win big" "W/win-big.html")
    ("win win" "W/win-win.html")
    ("Winchester" "W/Winchester.html")
    ("windoid" "W/windoid.html")
    ("window shopping" "W/window-shopping.html")
    ("Windowsitis" "W/Windowsitis.html")
    ("Windoze" "W/Windoze.html")
    ("winged comments" "W/winged-comments.html")
    ("winkey" "W/winkey.html")
    ("winnage" "W/winnage.html")
    ("winner" "W/winner.html")
    ("winnitude" "W/winnitude.html")
    ("Wintel" "W/Wintel.html")
    ("Wintendo" "W/Wintendo.html")
    ("wired" "W/wired.html")
    ("wirehead" "W/wirehead.html")
    ("wirewater" "W/wirewater.html")
    ("wish list" "W/wish-list.html")
    ("within delta of" "W/within-delta-of.html")
    ("within epsilon of" "W/within-epsilon-of.html")
    ("wizard" "W/wizard.html")
    ("Wizard Book" "W/Wizard-Book.html")
    ("wizard hat" "W/wizard-hat.html")
    ("wizard mode" "W/wizard-mode.html")
    ("wizardly" "W/wizardly.html")
    ("wok-on-the-wall" "W/wok-on-the-wall.html")
    ("womb box" "W/womb-box.html")
    ("WOMBAT" "W/WOMBAT.html")
    ("womble" "W/womble.html")
    ("wonky" "W/wonky.html")
    ("workaround" "W/workaround.html")
    ("working as designed" "W/working-as-designed.html")
    ("worm" "W/worm.html")
    ("wormhole" "W/wormhole.html")
    ("wound around the axle" "W/wound-around-the-axle.html")
    ("wrap around" "W/wrap-around.html")
    ("write-only code" "W/write-only-code.html")
    ("write-only language" "W/write-only-language.html")
    ("write-only memory" "W/write-only-memory.html")
    ("Wrong Thing" "W/Wrong-Thing.html")
    ("wugga wugga" "W/wugga-wugga.html")
    ("wumpus" "W/wumpus.html")
    ("WYSIAYG" "W/WYSIAYG.html")
    ("WYSIWYG" "W/WYSIWYG.html")
    ("X" "X/X.html")
    ("XEROX PARC" "X/XEROX-PARC.html")
    ("XOFF" "X/XOFF.html")
    ("XON" "X/XON.html")
    ("xor" "X/xor.html")
    ("xref" "X/xref.html")
    ("XXX" "X/XXX.html")
    ("xyzzy" "X/xyzzy.html")
    ("YA-" "Y/YA-.html")
    ("YABA" "Y/YABA.html")
    ("YAFIYGI" "Y/YAFIYGI.html")
    ("yak shaving" "Y/yak-shaving.html")
    ("YAUN" "Y/YAUN.html")
    ("yellow card" "Y/yellow-card.html")
    ("yellow wire" "Y/yellow-wire.html")
    ("Yet Another" "Y/Yet-Another.html")
    ("YHBT" "Y/YHBT.html")
    ("YKYBHTLW" "Y/YKYBHTLW.html")
    ("YMMV" "Y/YMMV.html")
    ("You are not expected to understand this" "Y/You-are-not-expected-to-understand-this.html")
    ("You know you've been hacking too long when" "Y/You-know-you-ve-been-hacking-too-long-when.html")
    ("Your mileage may vary" "Y/Your-mileage-may-vary.html")
    ("Yow!" "Y/Yow-.html")
    ("yoyo mode" "Y/yoyo-mode.html")
    ("Yu-Shiang Whole Fish" "Y/Yu-Shiang-Whole-Fish.html")
    ("zap" "Z/zap.html")
    ("zapped" "Z/zapped.html")
    ("Zawinski's Law" "Z/Zawinskis-Law.html")
    ("zbeba" "Z/zbeba.html")
    ("zen" "Z/zen.html")
    ("zero" "Z/zero.html")
    ("zero-content" "Z/zero-content.html")
    ("Zero-One-Infinity Rule" "Z/Zero-One-Infinity-Rule.html")
    ("zeroth" "Z/zeroth.html")
    ("zigamorph" "Z/zigamorph.html")
    ("zip" "Z/zip.html")
    ("zipperhead" "Z/zipperhead.html")
    ("zombie" "Z/zombie.html")
    ("zorch" "Z/zorch.html")
    ("Zork" "Z/Zork.html")
    ("zorkmid" "Z/zorkmid.html")))

(defvar jargon-file-root "http://www.catb.org/~esr/jargon/html/")

(defun jargon-url (term)
  "Lookup TERM in the Jargon File.

If `current-prefix-arg' is non-nil, inserts TERM's URL at point, else,
browses to TERM's URL, see `browse-url'."
  (interactive (list (completing-read "Word: "
                                      jargon-words)))
  (let ((url (format "%s%s" jargon-file-root
                     (second (assoc term jargon-words)))))
    (if current-prefix-arg
        (insert url)
        (browse-url url))))

(provide 'jargon)

;;; jargon.el ends here
